### ISSUE TITLE
nyc prevents test using child_process.spawn() from working properly on Windows

### ISSUE THREAD

**Issue by lpinca** [istanbuljs/nyc#1079]
## Test case

```js
// index.js

'use strict';

const { spawn } = require('child_process');
const { strictEqual } = require('assert');

const child = spawn('cmd', ['/c', 'node', '-v'], {
  stdio: 'inherit'
});

child.on('close', function(code) {
  strictEqual(code, 0);
});
```

Run `nyc node index.js`.

## Expected Behavior

Test passes.

## Observed Behavior

Test fails.

```
λ nyc node index.js
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module 'C:\Users\Luigi\Desktop\test\"C:\Users\Luigi\.node-spawn-wrap-12012-837c15def0bc\node"undefined'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at runMain (C:\Users\Luigi\.node-spawn-wrap-12012-837c15def0bc\node:68:10)
    at Function.<anonymous> (C:\Users\Luigi\.node-spawn-wrap-12012-837c15def0bc\node:171:5)
    at Object.<anonymous> (C:\Users\Luigi\AppData\Roaming\npm\node_modules\nyc\bin\wrap.js:21:4)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
assert.js:86
  throw new AssertionError(obj);
  ^

AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:

1 !== 0

    at ChildProcess.<anonymous> (C:\Users\Luigi\Desktop\test\index.js:1:1349)
    at ChildProcess.emit (events.js:193:13)
    at maybeClose (internal/child_process.js:999:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 index.js |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
```

### Troubleshooting steps
- [x] still occurrring when I put `cache: false` in my nyc config

## Environment Information

```
System:
  OS: Windows 10
  CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
  Memory: 3.88 GB / 7.98 GB
Binaries:
  Node: 11.14.0 - C:\Program Files\nodejs\node.EXE
  npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD
```

```
λ nyc --version
14.0.0
```

**Comment by lpinca** [comment]
It seems to be an issue with the bundled spawn-wrap but I'm not sure how it works. Also I'm not a Windows user. I'm only trying to make https://github.com/nodejs/citgm tests work on Windows.

FWIW the test passes with c8 (`c8 node index.js`).

**Comment by lpinca** [comment]
Closing as the issue is outside of nyc. I can reproduce with

```js
'use strict';

const wrap = require('spawn-wrap');
const cp = require('child_process');

if (process.argv[2] === 'wrap') {
  wrap.runMain();
} else {
  wrap([__filename, 'wrap']);
  cp.spawn('cmd', ['/c', 'node', '-v'], {
    stdio: 'inherit'
  });
}
```

Will reopen on https://github.com/tapjs/spawn-wrap. Sorry for the noise.

**Comment by coreyfarrell** [comment]
Might be that `cmd /c` rewrites PATH?  Something like the following should allow you to test it:
```js
console.log('parent', process.env.PATH);
cp.spawn('cmd', ['/c', 'node', '-e', 'console.log("child", process.env.PATH)']);
```

**Comment by lpinca** [comment]
It seems to be an issue in [`mungeCmd()`](https://github.com/tapjs/spawn-wrap/blob/7931ab5ca8732468efb115fc23b89cd7d96c5550/index.js#L143-L180).

There are a few open PRs that could potentially fix the issue on spawn-wrap but the library seems to lack maintenance.

I think a possible dirty workaround for my specific issue could be skipping [`mungeCmd()`](https://github.com/tapjs/spawn-wrap/blob/7931ab5ca8732468efb115fc23b89cd7d96c5550/index.js#L144-L146) by changing `/c` to `/C` [here](https://github.com/nodejs/citgm/blob/46e38095f8a4126e95c959ec576b1a596dca08d0/lib/spawn.js#L15).
