### ISSUE TITLE
Tests fail on native Windows cmd

### ISSUE THREAD

**Issue by XhmikosR** [istanbuljs/nyc#1248]
## Expected Behavior

Tests should pass

## Observed Behavior

Tests fail on Windows (10 is what I used)

## Environment Information

```
C:\Users\xmr\Desktop\nyc>npx envinfo@latest --preset nyc
npx: installed 1 in 1.173s

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Memory: 6.54 GB / 8.00 GB
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    istanbul-lib-coverage: ^3.0.0 => 3.0.0
    istanbul-lib-hook: ^3.0.0 => 3.0.0
    istanbul-lib-instrument: ^4.0.0 => 4.0.0
    istanbul-lib-processinfo: ^2.0.2 => 2.0.2
    istanbul-lib-report: ^3.0.0 => 3.0.0
    istanbul-lib-source-maps: ^4.0.0 => 4.0.0
    istanbul-reports: ^3.0.0 => 3.0.0
    source-map-support: ^0.5.16 => 0.5.16

```

## Test output

<details><summary>Log</summary>

```
C:\Users\xmr\Desktop\nyc>git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

C:\Users\xmr\Desktop\nyc>node -v && npm -v
v12.14.0
6.13.4

C:\Users\xmr\Desktop\nyc>npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 847 packages from 320 contributors and audited 3391 packages in 12.536s

20 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\Users\xmr\Desktop\nyc>npm t

> nyc@15.0.0 pretest C:\Users\xmr\Desktop\nyc
> npm run lint && npm run clean && npm run instrument


> nyc@15.0.0 lint C:\Users\xmr\Desktop\nyc
> standard


> nyc@15.0.0 clean C:\Users\xmr\Desktop\nyc
> node ./npm-run-clean.js


> nyc@15.0.0 instrument C:\Users\xmr\Desktop\nyc
> node ./build-self-coverage.js


> nyc@15.0.0 test C:\Users\xmr\Desktop\nyc
> tap

 PASS  test/add-all-files.js 13 OK 2s
 PASS  test/cache.js 2 OK 5s
 PASS  test/config.js 15 OK 153.719ms
 PASS  test/eager.js 6 OK 1s
 PASS  test/cwd.js 4 OK 99.999ms
 PASS  test/instrument.js 63 OK 10s
 PASS  test/issue-190.js 2 OK 10.033ms
 FAIL  test/nyc-integration.js
 ✖ should be equal


  t.equal(status, 0)
----^
  t.equal(stderr, '')
  t.matchSnapshot(stdout, 'stdout')

  test: test/nyc-integration.js can run "npm test" which directly invokes a test file
  found: 7
  wanted: 0
  compare: ===
  at:
    line: 11
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:11:5)

 FAIL  test/nyc-integration.js
 ✖ should be equal

  t.equal(status, 0)
  t.equal(stderr, '')
----^
  t.matchSnapshot(stdout, 'stdout')
}

  test: test/nyc-integration.js can run "npm test" which directly invokes a test file
  found: "Error: Failed to replace env in config: ${APPDATA}

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:415:13

    \    at String.replace (<anonymous>)

    \    at envReplace (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:411:12)

    \    at parseField (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:389:7)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:330:24

    \    at Array.forEach (<anonymous>)

    \    at Conf.add (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:328:23)

    \    at ConfigChain.addString (C:/Program
    Files/nodejs/node_modules/npm/node_modules/config-chain/index.js:244:8)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:316:10)

    \    at C:/Program
    Files/nodejs/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16

    TypeError: Cannot read property 'loaded' of undefined

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)

    \    at errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)

    \    at C:/Program Files/nodejs/node_modules/npm/bin/npm-cli.js:78:20

    \    at cb (C:/Program Files/nodejs/node_modules/npm/lib/npm.js:225:22)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/npm.js:263:24

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:81:7

    \    at Array.forEach (<anonymous>)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:80:13)

    \    at Conf.f (C:/Program
    Files/nodejs/node_modules/npm/node_modules/once/once.js:25:25)

    \    at Conf.emit (events.js:210:5)

    C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97\r

    \  var doExit = npm.config.loaded ? npm.config.get('_exit') : true\r

    \                          ^\r

    \r

    TypeError: Cannot read property 'loaded' of undefined\r

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)\r

    \    at process.errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)\r

    \    at process.emit (events.js:210:5)\r

    \    at processEmit [as emit]
    (C:/Users/xmr/Desktop/nyc/node_modules/signal-exit/index.js:155:32)\r

    \    at process._fatalException (internal/process/execution.js:150:25)\r

    Error: Failed to replace env in config: ${APPDATA}

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:415:13

    \    at String.replace (<anonymous>)

    \    at envReplace (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:411:12)

    \    at parseField (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:389:7)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:330:24

    \    at Array.forEach (<anonymous>)

    \    at Conf.add (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:328:23)

    \    at ConfigChain.addString (C:/Program
    Files/nodejs/node_modules/npm/node_modules/config-chain/index.js:244:8)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:316:10)

    \    at C:/Program
    Files/nodejs/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16

    TypeError: Cannot read property 'loaded' of undefined

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)

    \    at errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)

    \    at C:/Program Files/nodejs/node_modules/npm/bin/npm-cli.js:78:20

    \    at cb (C:/Program Files/nodejs/node_modules/npm/lib/npm.js:225:22)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/npm.js:263:24

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:81:7

    \    at Array.forEach (<anonymous>)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:80:13)

    \    at Conf.f (C:/Program
    Files/nodejs/node_modules/npm/node_modules/once/once.js:25:25)

    \    at Conf.emit (events.js:210:5)

    C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97\r

    \  var doExit = npm.config.loaded ? npm.config.get('_exit') : true\r

    \                          ^\r

    \r

    TypeError: Cannot read property 'loaded' of undefined\r

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)\r

    \    at process.errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)\r

    \    at process.emit (events.js:210:5)\r

    \    at processEmit [as emit]
    (C:/Users/xmr/Desktop/nyc/node_modules/signal-exit/index.js:155:32)\r

    \    at process._fatalException (internal/process/execution.js:150:25)\r\n"
  wanted: ""
  compare: ===
  at:
    line: 12
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:12:5)

 FAIL  test/nyc-integration.js
 ✖ stdout

  t.equal(stderr, '')
  t.matchSnapshot(stdout, 'stdout')
----^
}

  --- expected
  +++ actual
  @@ -1,11 +1,6 @@
  +----------|---------|----------|---------|---------|-------------------
  +File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
  +----------|---------|----------|---------|---------|-------------------
  +All files |       0 |        0 |       0 |       0 |
  +----------|---------|----------|---------|---------|-------------------
  -> @ test .
  -> node ./half-covered.js
  -
  ------------------|---------|----------|---------|---------|-------------------
  -File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
  ------------------|---------|----------|---------|---------|-------------------
  -All files        |      50 |       50 |     100 |      50 |
  - half-covered.js |      50 |       50 |     100 |      50 | 6-8
  ------------------|---------|----------|---------|---------|-------------------
  -

  test: test/nyc-integration.js can run "npm test" which directly invokes a test file
  at:
    line: 13
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:13:5)

 FAIL  test/nyc-integration.js
 ✖ should be equal


  t.equal(status, 0)
----^
  t.equal(stderr, '')
  t.matchSnapshot(stdout, 'stdout')

  test: test/nyc-integration.js can run "npm test" which indirectly invokes a test file
  found: 7
  wanted: 0
  compare: ===
  at:
    line: 11
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:11:5)

 FAIL  test/nyc-integration.js
 ✖ should be equal

  t.equal(status, 0)
  t.equal(stderr, '')
----^
  t.matchSnapshot(stdout, 'stdout')
}

  test: test/nyc-integration.js can run "npm test" which indirectly invokes a test file
  found: "Error: Failed to replace env in config: ${APPDATA}

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:415:13

    \    at String.replace (<anonymous>)

    \    at envReplace (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:411:12)

    \    at parseField (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:389:7)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:330:24

    \    at Array.forEach (<anonymous>)

    \    at Conf.add (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:328:23)

    \    at ConfigChain.addString (C:/Program
    Files/nodejs/node_modules/npm/node_modules/config-chain/index.js:244:8)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:316:10)

    \    at C:/Program
    Files/nodejs/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16

    TypeError: Cannot read property 'loaded' of undefined

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)

    \    at errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)

    \    at C:/Program Files/nodejs/node_modules/npm/bin/npm-cli.js:78:20

    \    at cb (C:/Program Files/nodejs/node_modules/npm/lib/npm.js:225:22)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/npm.js:263:24

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:81:7

    \    at Array.forEach (<anonymous>)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:80:13)

    \    at Conf.f (C:/Program
    Files/nodejs/node_modules/npm/node_modules/once/once.js:25:25)

    \    at Conf.emit (events.js:210:5)

    C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97\r

    \  var doExit = npm.config.loaded ? npm.config.get('_exit') : true\r

    \                          ^\r

    \r

    TypeError: Cannot read property 'loaded' of undefined\r

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)\r

    \    at process.errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)\r

    \    at process.emit (events.js:210:5)\r

    \    at processEmit [as emit]
    (C:/Users/xmr/Desktop/nyc/node_modules/signal-exit/index.js:155:32)\r

    \    at process._fatalException (internal/process/execution.js:150:25)\r

    Error: Failed to replace env in config: ${APPDATA}

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:415:13

    \    at String.replace (<anonymous>)

    \    at envReplace (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:411:12)

    \    at parseField (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:389:7)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:330:24

    \    at Array.forEach (<anonymous>)

    \    at Conf.add (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:328:23)

    \    at ConfigChain.addString (C:/Program
    Files/nodejs/node_modules/npm/node_modules/config-chain/index.js:244:8)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:316:10)

    \    at C:/Program
    Files/nodejs/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16

    TypeError: Cannot read property 'loaded' of undefined

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)

    \    at errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)

    \    at C:/Program Files/nodejs/node_modules/npm/bin/npm-cli.js:78:20

    \    at cb (C:/Program Files/nodejs/node_modules/npm/lib/npm.js:225:22)

    \    at C:/Program Files/nodejs/node_modules/npm/lib/npm.js:263:24

    \    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:81:7

    \    at Array.forEach (<anonymous>)

    \    at Conf.<anonymous> (C:/Program
    Files/nodejs/node_modules/npm/lib/config/core.js:80:13)

    \    at Conf.f (C:/Program
    Files/nodejs/node_modules/npm/node_modules/once/once.js:25:25)

    \    at Conf.emit (events.js:210:5)

    C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97\r

    \  var doExit = npm.config.loaded ? npm.config.get('_exit') : true\r

    \                          ^\r

    \r

    TypeError: Cannot read property 'loaded' of undefined\r

    \    at exit (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)\r

    \    at process.errorHandler (C:/Program
    Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)\r

    \    at process.emit (events.js:210:5)\r

    \    at processEmit [as emit]
    (C:/Users/xmr/Desktop/nyc/node_modules/signal-exit/index.js:155:32)\r

    \    at process._fatalException (internal/process/execution.js:150:25)\r\n"
  wanted: ""
  compare: ===
  at:
    line: 12
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:12:5)

 FAIL  test/nyc-integration.js
 ✖ stdout

  t.equal(stderr, '')
  t.matchSnapshot(stdout, 'stdout')
----^
}

  --- expected
  +++ actual
  @@ -1,19 +1,6 @@
  +----------|---------|----------|---------|---------|-------------------
  +File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
  +----------|---------|----------|---------|---------|-------------------
  +All files |       0 |        0 |       0 |       0 |
  +----------|---------|----------|---------|---------|-------------------
  -> @ test .
  -> npm run test:deeper
  -
  -
  -> @ test:deeper .
  -> npm run test:even-deeper
  -
  -
  -> @ test:even-deeper .
  -> node ./half-covered.js
  -
  ------------------|---------|----------|---------|---------|-------------------
  -File             | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
  ------------------|---------|----------|---------|---------|-------------------
  -All files        |      50 |       50 |     100 |      50 |
  - half-covered.js |      50 |       50 |     100 |      50 | 6-8
  ------------------|---------|----------|---------|---------|-------------------
  -

  test: test/nyc-integration.js can run "npm test" which indirectly invokes a test file
  at:
    line: 13
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:13:5)

 FAIL  test/nyc-integration.js
 ✖ should be equal


  t.equal(status, 0)
----^
  t.equal(stderr, '')
  t.matchSnapshot(stdout, 'stdout')

  test: test/nyc-integration.js recursive run does not throw
  found: 1
  wanted: 0
  compare: ===
  at:
    line: 11
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:11:5)
    runMicrotasks (<anonymous>)

 FAIL  test/nyc-integration.js
 ✖ should be equal

  t.equal(status, 0)
  t.equal(stderr, '')
----^
  t.matchSnapshot(stdout, 'stdout')
}

  test: test/nyc-integration.js recursive run does not throw
  found: "'true' is not recognized as an internal or external command,\r

    operable program or batch file.\r

    events.js:187\r

    \      throw er; // Unhandled 'error' event\r

    \      ^\r

    \r

    Error: spawn true ENOENT\r

    \    at notFoundError
    (C:/Users/xmr/Desktop/nyc/node_modules/cross-spawn/lib/enoent.js:6:26)\r

    \    at verifyENOENT
    (C:/Users/xmr/Desktop/nyc/node_modules/cross-spawn/lib/enoent.js:40:16)\r

    \    at ChildProcess.cp.emit
    (C:/Users/xmr/Desktop/nyc/node_modules/cross-spawn/lib/enoent.js:27:25)\r

    \    at Process.ChildProcess._handle.onexit
    (internal/child_process.js:272:12)\r

    Emitted 'error' event on ChildProcess instance at:\r

    \    at ChildProcess.cp.emit
    (C:/Users/xmr/Desktop/nyc/node_modules/cross-spawn/lib/enoent.js:30:37)\r

    \    at Process.ChildProcess._handle.onexit
    (internal/child_process.js:272:12) {\r

    \  code: 'ENOENT',\r

    \  errno: 'ENOENT',\r

    \  syscall: 'spawn true',\r

    \  path: 'true',\r

    \  spawnargs: []\r

    }\r\n"
  wanted: ""
  compare: ===
  at:
    line: 12
    column: 5
    file: test/helpers/test-success.js
    function: testSuccess
  stack: |
    testSuccess (test/helpers/test-success.js:12:5)
    runMicrotasks (<anonymous>)

 FAIL  test/nyc-integration.js 8 failed of 221 16s
 ✖ should be equal
 ✖ should be equal
 ✖ stdout
 ✖ should be equal
 ✖ should be equal
 ✖ stdout
 ✖ should be equal
 ✖ should be equal

 PASS  test/parser-plugins.js 6 OK 949.284ms
 PASS  test/process-args.js 5 OK 33.029ms
 PASS  test/processinfo.js 21 OK 2s
 PASS  test/report.js 3 OK 228.821ms
 PASS  test/should-instrument.js 23 OK 140.802ms
 PASS  test/source-map-support.js 2 OK 590.096ms
 PASS  test/temp-dir.js 15 OK 2s
 PASS  test/tsc.js 6 OK 2s
 PASS  test/wrap.js 12 OK 854.404ms


  🌈 SUMMARY RESULTS 🌈


 FAIL  test/nyc-integration.js 8 failed of 221 16s
 ✖ should be equal
 ✖ should be equal
 ✖ stdout
 ✖ should be equal
 ✖ should be equal
 ✖ stdout
 ✖ should be equal
 ✖ should be equal

Suites:   1 failed, 16 passed, 17 of 17 completed
Asserts:  8 failed, 411 passed, of 419
Time:     47s
npm ERR! Test failed.  See above for more details.
```

</details>

@coreyfarrell there you go :)

Might be worth looking into GitHub Actions CI (but the default shell is PorwerShell there, so I'm not sure if these will happen without switching to cmd)

**Comment by XhmikosR** [comment]
Feel free to ping me for any more info/tests and I can also make a PR to switch to GitHub Actions CI if you want later.

**Comment by XhmikosR** [comment]
Just a wild thought, this could be because Node is installed by default in `C:\Program Files\nodejs` which has a space in path?

**Comment by XhmikosR** [comment]
NVM, I spend a little more time debugging this and if I remove these tests then everything is green:

```diff
 test/nyc-integration.js | 23 -----------------------
 1 file changed, 23 deletions(-)

diff --git a/test/nyc-integration.js b/test/nyc-integration.js
index 5fd43a1..b6047ad 100644
--- a/test/nyc-integration.js
+++ b/test/nyc-integration.js
@@ -204,16 +204,6 @@ t.test('--use-spawn-wrap=false is functional', t => testSuccess(t, {
   args: ['--use-spawn-wrap=false', process.execPath, 'selfspawn-fibonacci.js', '5']
 }))
 
-t.test('can run "npm test" which directly invokes a test file', t => testSuccess(t, {
-  args: ['npm', 'test'],
-  cwd: path.resolve(fixturesCLI, 'run-npm-test')
-}))
-
-t.test('can run "npm test" which indirectly invokes a test file', t => testSuccess(t, {
-  args: ['npm', 'test'],
-  cwd: path.resolve(fixturesCLI, 'run-npm-test-recursive')
-}))
-
 t.test('nyc instrument single file to console', async t => {
   const { status, stderr, originalText } = await runNYC({
     tempDir: t.tempDir,
@@ -573,19 +563,6 @@ t.test('instrument with exclude-node-modules=false', async t => {
   t.match(stdout, 'fake-module-1')
 })
 
-t.test('recursive run does not throw', t => testSuccess(t, {
-  args: [
-    process.execPath,
-    nycBin,
-    process.execPath,
-    nycBin,
-    process.execPath,
-    nycBin,
-    'true'
-  ],
-  cwd: path.resolve(__dirname, 'fixtures/recursive-run')
-}))
-
 t.test('combines multiple coverage reports', async t => {
   await testSuccess(t, {
     args: ['merge', './merge-input']

```

```
Suites:   18 passed, 18 of 18 completed
Asserts:  413 passed, of 413
Time:     47s
```

So, at least this should narrow it down. I'll see if I can pinpoint the cause myself, unless someone else beats me to it.

**Comment by coreyfarrell** [comment]
I've cleaned up error message received from npm, in the details here.  @isaacs do you have any ideas what we're looking at here?  npm 6.13.4.
<details>
<pre>
Error: Failed to replace env in config: ${APPDATA}
    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:411:12)
    at parseField (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:389:7)
    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (C:/Program Files/nodejs/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:316:10)
    at C:/Program Files/nodejs/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)
    at errorHandler (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)
    at C:/Program Files/nodejs/node_modules/npm/bin/npm-cli.js:78:20
    at cb (C:/Program Files/nodejs/node_modules/npm/lib/npm.js:225:22)
    at C:/Program Files/nodejs/node_modules/npm/lib/npm.js:263:24
    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:80:13)
    at Conf.f (C:/Program Files/nodejs/node_modules/npm/node_modules/once/once.js:25:25)
    at Conf.emit (events.js:210:5)

C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)
    at process.errorHandler (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:210:5)
    at processEmit [as emit] (C:/Users/xmr/Desktop/nyc/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (internal/process/execution.js:150:25)

Error: Failed to replace env in config: ${APPDATA}
    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:415:13
    at String.replace (<anonymous>)
    at envReplace (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:411:12)
    at parseField (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:389:7)
    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:330:24
    at Array.forEach (<anonymous>)
    at Conf.add (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:328:23)
    at ConfigChain.addString (C:/Program Files/nodejs/node_modules/npm/node_modules/config-chain/index.js:244:8)
    at Conf.<anonymous> (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:316:10)
    at C:/Program Files/nodejs/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:115:16

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)
    at errorHandler (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)
    at C:/Program Files/nodejs/node_modules/npm/bin/npm-cli.js:78:20
    at cb (C:/Program Files/nodejs/node_modules/npm/lib/npm.js:225:22)
    at C:/Program Files/nodejs/node_modules/npm/lib/npm.js:263:24
    at C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (C:/Program Files/nodejs/node_modules/npm/lib/config/core.js:80:13)
    at Conf.f (C:/Program Files/nodejs/node_modules/npm/node_modules/once/once.js:25:25)
    at Conf.emit (events.js:210:5)

C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:97:27)
    at process.errorHandler (C:/Program Files/nodejs/node_modules/npm/lib/utils/error-handler.js:216:3)
    at process.emit (events.js:210:5)
    at processEmit [as emit] (C:/Users/xmr/Desktop/nyc/node_modules/signal-exit/index.js:155:32)
    at process._fatalException (internal/process/execution.js:150:25)
</pre>
</details>

**Comment by XhmikosR** [comment]
I just want to point out that I only hit this here when running the tests. First time I see this error on my VM. I can publish and install packages and do everything else just fine. I will try tomorrow on another Windows machine just in case.

**Comment by isaacs** [comment]
> `Error: Failed to replace env in config: ${APPDATA}`

This indicates that the string `${APPDATA}` is found in one of the config files npm is trying to load, but it can't find a `process.env.APPDATA` to sub in there for the value.

**Comment by coreyfarrell** [comment]
I just double-checked, `grep -R . -e APPDATA` from the nyc repo shows 1 result - `./node_modules/resolve/appveyor.yml` which would have no effect on nyc's testing.  Also odd that this is only happening in the recursive `npm test`.

There are matches to `APPDATA` in the npm module though, maybe this is because the `env` passed to new spawns from the nyc tests start from empty?

**Comment by XhmikosR** [comment]
I also checked and I have the environment variables just fine on my VM:

```
C:\Users\xmr\Desktop>set | findstr APPDATA
APPDATA=C:\Users\xmr\AppData\Roaming
LOCALAPPDATA=C:\Users\xmr\AppData\Local
```

**Comment by XhmikosR** [comment]
The only thing I can think of is a test overwriting some variables so the OS variables aren't available, hence the error. BTW it seems the failing tests are the recursive ones. If you have any ideas how to debug this please let me know and I'd be happy to provide more info.

I might set up AppVeyor/GitHub Actions CI to my fork to see if this happens there too.

**Comment by XhmikosR** [comment]
Alright, I just set up both GitHub Actions CI and AppVeyor.

* https://github.com/XhmikosR/nyc/runs/364878400
* https://ci.appveyor.com/project/XhmikosR/nyc/build/job/wa9rpujp40of8u5n

It seems on GitHub Actions CI macOS builds fail but not Windows. AppVeyor properly fails like my environment, which makes sense since it's the closest to native Windows as it gets.

**Comment by coreyfarrell** [comment]
@XhmikosR what happens if you modify test/helpers/run-nyc.js, after https://github.com/istanbuljs/nyc/blob/master/test/helpers/run-nyc.js#L6-L8 add:

```js
if ('APPDATA' in path.env) {
  envPath.APPDATA = path.env.APPDATA
}
```

**Comment by XhmikosR** [comment]
* Branch: https://github.com/istanbuljs/nyc/compare/master...XhmikosR:appveyor
* https://ci.appveyor.com/project/XhmikosR/nyc/builds/29775359/job/imjidwwgasgj4dtq

BTW we could just add AppVeyor to the repo; it seems like the best way to test Windows from my experience.

**Comment by coreyfarrell** [comment]
Note: I edited my previous comment as the code was bad, referred to `path.env` instead of `process.env` (sorry).

> BTW we could just add AppVeyor to the repo; it seems like the best way to test Windows from my experience.

I'll look into this when I get a chance.

**Comment by XhmikosR** [comment]
I invited you to my fork for the time being, but I can just submit a PR with my appveyor.yml assuming you add the repo to AppVeyor yourself.

**Comment by XhmikosR** [comment]
https://ci.appveyor.com/project/XhmikosR/nyc/builds/29775420

It seems it's passing now

**Comment by XhmikosR** [comment]
Maybe we should destructure `process.env` in `envPath`? Or is it intentional that you don't want `envPath` to have any other variables?

**Comment by coreyfarrell** [comment]
> Maybe we should destructure `process.env` in `envPath`? Or is it intentional that you don't want `envPath` to have any other variables?

It's intentional, reduces the potential for the system environment to change the snapshots.  If you don't mind please submit a PR that conditionally sets `envPath.APPDATA` in test/helpers/run-nyc.js.

**Comment by XhmikosR** [comment]
But it's your patch :)

**Comment by coreyfarrell** [comment]
> But it's your patch :)

Fair enough, I'm really not concerned with credit for a 3 line patch (I release all copyright claim) but I can try pushing it later.

**Comment by XhmikosR** [comment]
I'm just a strong believer of giving credit where it's due, that's all.

**Comment by coreyfarrell** [comment]
Looks like appveyor is not experiencing issues with node.js 10 / 12?  Ref https://github.com/nodejs/node/issues/25484

I've just installed appveyor to the istanbuljs org, would you like to submit a PR to setup appveyor in nyc?

**Comment by XhmikosR** [comment]
I'm not aware of any issues and as you can see from my fork it seems to work. But I haven't added v13. I will make a PR. Do you want me to add a README.md badge too? And remove Windows from Travis CI in the same PR?

**Comment by coreyfarrell** [comment]
Yes the badge can go after travis / before the coverage badge.  Please do remove Windows from travis including the `matrix` structure which only exists to filter out broken versions of Windows.

Side note I don't believe I need access to your fork of nyc, please feel free to revoke the invite.  I'm not going to decline in case github has some algorithm which views declines as a negative against your account.

**Comment by XhmikosR** [comment]
All good, I just did it in case you needed to play with AppVeyor without adding it to the repo.

I'll make a PR soon.
