### ISSUE TITLE
nyc@15 new NYC() throws `TypeError: Cannot read property 'subprocessBin' of undefined`

### ISSUE THREAD

**Issue by axelssonHakan** [istanbuljs/nyc#1262]
## Expected Behavior
Can't find any information about this changed behaviour. Is it an unexpected breaking change?

## Observed Behavior
I'm using NYC/instanbul/puppeteer to get the test coverage after finished a test run.
I have done this using an "in process" API call to NYC
```
  const nyc = new NYC();
  await nyc.report();
```
But after NYC@15 this throws an error:
```
  TypeError: Cannot read property 'subprocessBin' of undefined
    at new NYC (node_modules/nyc/index.js:49:33)
    at _callee4$ (test/e2e/_setup.spec.js:65:15)
    at tryCatch (node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/circleci/catwalk/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Context.<anonymous> (node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
```

**Comment by coreyfarrell** [comment]
nyc is an application, use of the `require('nyc')` API is not documented or supported.  That said you ***might*** work around this issue by passing an empty option to nyc `new NYC({})`.

That said my strong advice is to simply execute `nyc report`.  If you need to find the nyc binary to spawn from node.js code with `child_process` you can use `require.resolve('.bin/nyc')`.
