### ISSUE TITLE
`return 0n` breaks nyc coverage

### ISSUE THREAD

**Issue by philz** [istanbuljs/nyc#1369]
## Link to bug demonstration repository

https://github.com/philz/nyc-bug is a one-file, 4-line repro. I encountered this bug in a large TypeScript code base, and I was able to work around it with assigning the bigint to a variable, but this was very surprising.

## Expected Behavior

Coverage should work.

## Observed Behavior

The instrumented code is `return0n` rather than `return 0n`, or so it seems.

```
$./node_modules/.bin/nyc node index.js
/Users/philip/src/nyc-bug/index.js:2
cov_235y2cz5ul=function(){return actualCoverage;};}return actualCoverage;}cov_235y2cz5ul();function f(){cov_235y2cz5ul().f[0]++;cov_235y2cz5ul().s[0]++;return0n;}cov_235y2cz5ul().s[1]++;f();
                                                                                                                                                        ^

ReferenceError: return0n is not defined
    at f (/Users/philip/src/nyc-bug/index.js:2:153)
    at Object.<anonymous> (/Users/philip/src/nyc-bug/index.js:2:187)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Module.replacementCompile (/Users/philip/src/nyc-bug/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Object.<anonymous> (/Users/philip/src/nyc-bug/node_modules/append-transform/index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |     100 |      100 |     100 |     100 |                   
 index.js |     100 |      100 |     100 |     100 |                   
----------|---------|----------|---------|---------|-------------------
```

### Troubleshooting steps

`c8` works fine with this. I've tried upgrading nyc, but my demo repo has a recent version installed.

## Environment Information

This happens on Linux as well.

```
$npx envinfo@latest --preset nyc
npx: installed 1 in 1.846s

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 173.98 MB / 32.00 GB
  Binaries:
    Node: 12.14.1 - ~/h/node/env-12.14.1/bin/node
    Yarn: 1.21.1 - ~/h/node/env-12.14.1/bin/yarn
    npm: 6.13.4 - ~/h/node/env-12.14.1/bin/npm
  npmPackages:
    nyc: ^15.1.0 => 15.1.0 
```

**Comment by coreyfarrell** [comment]
Thanks for the repository, I've investigated and this looks like a bug in babel.  I've reported at https://github.com/babel/babel/issues/12423.

The workaround for now is to set `compact: false` in your nyc configuration.

**Comment by coreyfarrell** [comment]
Closing this issue as a fix to the associated bug has been merged to the main branch of babel.  The fix will be available upon the next release of `@babel/generator`.

**Comment by philz** [comment]
Thank you @coreyfarrell !
