### ISSUE TITLE
Mocha -chai Test cases is running but coverage is unknown

### ISSUE THREAD

**Issue by DKhateek1372** [istanbuljs/nyc#1385]
"scripts": {
    "start": "nodemon .",
    "test": "nyc --reporter=html --reporter=text mocha --timeout=5000",
    "coverage": "nyc -x \"**/test/**\" --reporter=cobertura --reporter=html mocha ./test/test.js"
  },
  
  this is my package.json file

![image](https://user-images.githubusercontent.com/30972035/106876500-c6066900-66fd-11eb-945d-6821f0d4682b.png)

**Comment by DKhateek1372** [comment]
`$ npm run coverage

> NodeExpress@1.0.0 coverage C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS
> nyc --reporter=text --reporter=text-summary npm test '**/*.js'


> NodeExpress@1.0.0 test C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS
> mocha --timeout 100000 --exit "'**/*.js'"


ReferenceError: document is not defined
    at init (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\coverage\block-navigation.js:20:35)
    at Object.<anonymous> (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\coverage\block-navigation.js:78:3)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Module.replacementCompile (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\node_modules\append-transform\index.js:60:13)
    at Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Object.<anonymous> (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\node_modules\append-transform\index.js:64:4)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.exports.requireOrImport (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\node_modules\mocha\lib\esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\node_modules\mocha\lib\esm-utils.js:33:34)
    at async singleRun (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at async Object.exports.handler (C:\Users\deepak.khateek\Documents\WorkSpace\Projects\PEOS\NodeJS\node_modules\mocha\lib\cli\run.js:362:5)
npm ERR! Test failed.  See above for more details.
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! NodeExpress@1.0.0 coverage: `nyc --reporter=text --reporter=text-summary npm test '**/*.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the NodeExpress@1.0.0 coverage script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\deepak.khateek\AppData\Roaming\npm-cache\_logs\2021-02-10T04_41_33_765Z-debug.log
`


I am getting error document is not define.
This is file Code where this error is generating. 
Please search for **document.querySelectorAll(selector);**

`/* eslint-disable */
var jumpToCode = (function init() {
    // Classes of code we would like to highlight in the file view
    var missingCoverageClasses = ['.cbranch-no', '.cstat-no', '.fstat-no'];

    // Elements to highlight in the file listing view
    var fileListingElements = ['td.pct.low'];

    // We don't want to select elements that are direct descendants of another match
    var notSelector = ':not(' + missingCoverageClasses.join('):not(') + ') > '; // becomes `:not(a):not(b) > `

    // Selecter that finds elements on the page to which we can jump
    var selector =
        fileListingElements.join(', ') +
        ', ' +
        notSelector +
        missingCoverageClasses.join(', ' + notSelector); // becomes `:not(a):not(b) > a, :not(a):not(b) > b`

    // The NodeList of matching elements
    var missingCoverageElements = document.querySelectorAll(selector);

    var currentIndex;

    function toggleClass(index) {
        missingCoverageElements
            .item(currentIndex)
            .classList.remove('highlighted');
        missingCoverageElements.item(index).classList.add('highlighted');
    }

    function makeCurrent(index) {
        toggleClass(index);
        currentIndex = index;
        missingCoverageElements.item(index).scrollIntoView({
            behavior: 'smooth',
            block: 'center',
            inline: 'center'
        });
    }

    function goToPrevious() {
        var nextIndex = 0;
        if (typeof currentIndex !== 'number' || currentIndex === 0) {
            nextIndex = missingCoverageElements.length - 1;
        } else if (missingCoverageElements.length > 1) {
            nextIndex = currentIndex - 1;
        }

        makeCurrent(nextIndex);
    }

    function goToNext() {
        var nextIndex = 0;

        if (
            typeof currentIndex === 'number' &&
            currentIndex < missingCoverageElements.length - 1
        ) {
            nextIndex = currentIndex + 1;
        }

        makeCurrent(nextIndex);
    }

    return function jump(event) {
        switch (event.which) {
            case 78: // n
            case 74: // j
                goToNext();
                break;
            case 66: // b
            case 75: // k
            case 80: // p
                goToPrevious();
                break;
        }
    };
})();
window.addEventListener('keydown', jumpToCode);
`
