### ISSUE TITLE
source maps in stack traces for transpiled typescript are wrong

### ISSUE THREAD

**Issue by scottbessler** [istanbuljs/nyc#1409]
## Link to bug demonstration repository

https://github.com/scottbessler/nyc-issue

## Expected Behavior

Expect to see source-mapped exception stacks like:

```
Error: bad
    at Object.bad (${pwd}/src/foo.ts:2:9)
    at [eval]:1:26
    ...
```

## Observed Behavior

```
Error: bad
    at Object.bad (${pwd}/lib/src/foo.js:2:252)
    at [eval]:1:26
    ...
```

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config
- [x] tried nearly all permutations of source map related flags, you can see 2 attempts in the scripts

## Environment Information

```
# paste the output here
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 153.89 MB / 32.00 GB
  Binaries:
    Node: 14.15.1 - ~/.volta/tools/image/node/14.15.1/bin/node
    Yarn: 1.22.4 - ~/.volta/tools/image/yarn/1.22.4/bin/yarn
    npm: 6.14.8 - ~/.volta/tools/image/node/14.15.1/bin/npm
  npmPackages:
    nyc: ^15.1.0 => 15.1.0 
    source-map-support: ^0.5.19 => 0.5.19 
    typescript: ^4.3.2 => 4.3.2 
```

**Comment by pfumagalli** [comment]
I found that forcedly setting `preserve-comments: false` in my `.nycrc` makes it work... By looking at the transpiled code, it seems that the old source map emitted by `tsc` is never removed, otherwise, and `source-map-support` gets totally confused by it!
