### ISSUE TITLE
Nyc report fails - TypeError: Cannot destructure property `start` of 'undefined' or 'null'

### ISSUE THREAD

**Issue by archfz** [istanbuljs/nyc#1438]
## Link to bug demonstration repository
https://github.com/archfz/nyc-issue-Xa24b
1. `npm i`
2. `npx nyc report --reporter=lcov --reporter=text-summary --report-dir=coverage`

## Expected Behavior

No error is thrown and report is generated.

## Observed Behavior

Error is thrown:
```
TypeError: Cannot destructure property `start` of 'undefined' or 'null'.
    at keyFromLoc (/home/archy/projects/holdmytable-frontend/node_modules/istanbul-lib-coverage/lib/file-coverage.js:43:21)
    at mergeProp (/home/archy/projects/holdmytable-frontend/node_modules/istanbul-lib-coverage/lib/file-coverage.js:50:16)
    at FileCoverage.merge (/home/archy/projects/holdmytable-frontend/node_modules/istanbul-lib-coverage/lib/file-coverage.js:208:27)
    at CoverageMap.addFileCoverage (/home/archy/projects/holdmytable-frontend/node_modules/istanbul-lib-coverage/lib/coverage-map.js:112:29)
    at /home/archy/projects/holdmytable-frontend/node_modules/istanbul-lib-coverage/lib/coverage-map.js:55:18
    at Array.forEach (<anonymous>)
    at CoverageMap.merge (/home/archy/projects/holdmytable-frontend/node_modules/istanbul-lib-coverage/lib/coverage-map.js:54:35)
    at /home/archy/projects/holdmytable-frontend/node_modules/nyc/index.js:433:13
    at async /home/archy/projects/holdmytable-frontend/node_modules/nyc/node_modules/p-map/index.js:57:15
```

I am doing the following:
- running mocha unit tests `nyc -r text-summary  mocha --recursive --colors ./test/unit/**/*.spec.ts`
- instrumentation of code typescript/react code with webpack and `istanbul-instrumenter-loader`
- cypress integration tests are run and `"@cypress/code-coverage": "^3.9.11"` generates nyc output
- running nyc report

```json
{
  "nyc": {
    "all": true,
    "include": [
      "src/**/*.ts",
      "src/**/*.tsx"
    ],
    "extension": [
      ".ts",
      ".tsx"
    ],
    "require": [
      "ts-node/register/transpile-only",
      "@babel/register"
    ],
    "sourceMap": true,
    "instrument": true
  },
}
```

### Troubleshooting steps
- [x] still occurring when I put `cache: false` in my nyc config
- [x] reproduces on latest version as well (istanbul-lib-coverage:3.2.0) 
- [x] reverting to `istanbul-lib-coverage:3.0.0` resolves issue, but brings another error `TypeError: Cannot read property 'loc' of undefined` for a different nyc output that I need (from cypress component testing) (probably should create a separate issue for that, but that doesn't reproduce on higher versions) 

## Environment Information
```
  System:
    OS: Linux 5.11 Ubuntu 21.10 21.10 (Impish Indri)
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 20.17 GB / 31.06 GB
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    npm: 6.14.15 - ~/.nvm/versions/node/v12.13.1/bin/npm
  npmPackages:
    @babel/core: ^7.4.5 => 7.12.10 
    @babel/plugin-syntax-dynamic-import: ^7.2.0 => 7.8.3 
    @babel/plugin-transform-runtime: ^7.8.3 => 7.12.10 
    @babel/preset-env: ^7.4.5 => 7.12.11 
    @babel/preset-react: ^7.0.0 => 7.12.10 
    @babel/register: ^7.8.3 => 7.12.10 
    babel-loader: ^8.0.6 => 8.2.2 
    babel-plugin-universal-import: ^4.0.0 => 4.0.2 
    istanbul-instrumenter-loader: ^3.0.1 => 3.0.1 
    istanbul-lib-coverage: 3.0.2 => 3.0.2 
    nyc: ^15.1.0 => 15.1.0 
    ts-node: ^8.5.4 => 8.10.2 
    typescript: ^3.8.3 => 3.9.10
```

**Comment by Verisana** [comment]
I have the same issue on `nyc@14.1.1`
