### ISSUE TITLE
HTML reporter reports 'Unable to lookup source'

### ISSUE THREAD

**Issue by jackson-at-bentley** [istanbuljs/nyc#1475]
## [Link to bug demonstration repository](https://github.com/jackson-at-bentley/minimal-mocha)

🍫☕️

## Expected behavior

I attempted to follow the installation instructions at [istanbul.js.org](https://istanbul.js.org/docs/tutorials/typescript/). I expect the HTML report generated by `nyc mocha` to have working links to view the coverage of each source file.

## Observed behavior

https://user-images.githubusercontent.com/107633044/175787832-1a150551-900f-4557-b02d-1ce96f03920e.mov

```
Unable to lookup source: /Users/jackson/Documents/mocha/src/file:/Users/jackson/Documents/mocha/src/hello.ts (ENOENT: no such file or directory, open '/Users/jackson/Documents/mocha/src/file:/Users/jackson/Documents/mocha/src/hello.ts')
Error: Unable to lookup source: /Users/jackson/Documents/mocha/src/file:/Users/jackson/Documents/mocha/src/hello.ts (ENOENT: no such file or directory, open '/Users/jackson/Documents/mocha/src/file:/Users/jackson/Documents/mocha/src/hello.ts')
    at Context.defaultSourceLookup [as sourceFinder] (/Users/jackson/Documents/mocha/node_modules/istanbul-lib-report/lib/context.js:17:15)
    at Context.getSource (/Users/jackson/Documents/mocha/node_modules/istanbul-lib-report/lib/context.js:71:21)
    at annotateSourceCode (/Users/jackson/Documents/mocha/node_modules/istanbul-reports/lib/html/annotator.js:232:40)
    at HtmlReport.onDetail (/Users/jackson/Documents/mocha/node_modules/istanbul-reports/lib/html/index.js:414:33)
    at Visitor.value (/Users/jackson/Documents/mocha/node_modules/istanbul-lib-report/lib/tree.js:38:38)
    at ReportNode.visit (/Users/jackson/Documents/mocha/node_modules/istanbul-lib-report/lib/tree.js:88:21)
    at /Users/jackson/Documents/mocha/node_modules/istanbul-lib-report/lib/tree.js:92:19
    at Array.forEach ()
    at ReportNode.visit (/Users/jackson/Documents/mocha/node_modules/istanbul-lib-report/lib/tree.js:91:28)
    at ReportTree.visit (/Users/jackson/Documents/mocha/node_modules/istanbul-lib-report/lib/tree.js:127:24)
```

### Troubleshooting steps
- Similar to the behavior described in [this issue](https://github.com/istanbuljs/istanbuljs/issues/129) from 2017.
- The call to [`remapCoverage(map.data)`](https://github.com/istanbuljs/nyc/blob/ab7c53b2f340b458789a746dff2abd3e2e4790c3/index.js#L433) in `nyc` seems to be clobbering the paths in the source map.

## Environment information
```
  System:
    OS: macOS 12.4
    CPU: (8) arm64 Apple M1
    Memory: 272.58 MB / 16.00 GB
  Binaries:
    Node: 18.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.12.1 - /opt/homebrew/bin/npm
  npmPackages:
    nyc: ^15.1.0 => 15.1.0
    source-map-support: ^0.5.21 => 0.5.21
    ts-node: ^10.8.1 => 10.8.1
    typescript: ^4.7.4 => 4.7.4
```

**Comment by amykhaylyshyn** [comment]
I'm getting the same error :(

**Comment by urska19** [comment]
I was having the same issue. Downgrading to ts-node: 10.8.0 resolved it for me. Hope it helps.

**Comment by pfedan** [comment]
same error here.

**Comment by pfedan** [comment]
There's an ongoing discussion about this problem on ts-node's side: https://github.com/TypeStrong/ts-node/issues/1790

According to them, it might as well be a bug on nyc's side.

**Comment by jackson-at-bentley** [comment]
Closing, this has been fixed in `ts-node`.
