### ISSUE TITLE
interferes with es6 functionality

### ISSUE THREAD

**Issue by rickharrison** [istanbuljs/nyc#304]
I am currently on node v6.3.0 and have a function like this:

```
function foo ({ foo = [], bar = [] } = {}) {

}
```

When I call the function, you would expect both `foo` and `bar` to equal `[]`. However, when I run a command such as `nyc mocha`, `foo` comes back as `undefined`. Is this related to nyc or is this something completely unrelated? Everything works as I expect until I run it under `nyc`

**Comment by bcoe** [comment]
@gotwarlost @rickharrison this feels like it's probably a bug with `istanbul-lib-instrument`, perhaps open the issue here?

**Comment by bcoe** [comment]
@rickharrison actually, mind running:

`npm cache clear; npm i nyc@next` rather than `npm i nyc`

this might already be fixed with the new changes we're about to release.

**Comment by rickharrison** [comment]
Thanks for helping out. All of my tests pass now, but I get this error at the end:

```
  2003 passing (2m)

module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/rickharrison/Development/meadow-api/node_modules/nyc/node_modules/istanbul-reports/lib/spec'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.module.exports.create (/Users/rickharrison/Development/meadow-api/node_modules/nyc/node_modules/istanbul-reports/index.js:10:20)
    at /Users/rickharrison/Development/meadow-api/node_modules/nyc/index.js:390:24
    at Array.forEach (native)
    at NYC.report (/Users/rickharrison/Development/meadow-api/node_modules/nyc/index.js:389:17)
    at report (/Users/rickharrison/Development/meadow-api/node_modules/nyc/bin/nyc.js:222:7)
    at /Users/rickharrison/Development/meadow-api/node_modules/nyc/bin/nyc.js:207:25
make: *** [cover-all] Error 1
```
