### ISSUE TITLE
[7.0.0] Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by tleunen** [istanbuljs/nyc#306]
I got notified of the new update of nyc 7.0.0 but I now get an error when running my tests.

```
/home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32
        writer.println('FN:' + [meta.decl.start.line, meta.name].join(','));
                                         ^

TypeError: Cannot read property 'start' of undefined
    at /home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:42
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (/home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at LcovReport.(anonymous function) [as onDetail] (/home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail] (/home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
    at visitChildren (/home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/home/ubuntu/react-clickdrag/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:126:5)
npm ERR! Test failed.  See above for more details.
```

Anything I should change in my setup?
My nyc config is this:
```
"nyc": {
    "sourceMap": false,
    "instrument": false,
    "reporter": [
      "lcov",
      "text"
    ]
  }
```
I'm also using the [coverage plugin](https://github.com/dtinth/babel-plugin-__coverage__).

**Comment by tleunen** [comment]
Updating all my deps + switching from the coverage for the new istanbul plugin resolved my issue.

**Comment by bcoe** [comment]
@tleunen awesome, let me know if you run into any more issues. merging the Istanbul and nyc project was a lot of work (lots of code changed).

**Comment by jedwards1211** [comment]
I'm getting 

```
/Users/andy/crater/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32
        writer.println('FN:' + [meta.decl.start.line, meta.name].join(','));
                                    ^

TypeError: Cannot read property 'decl' of undefined
```
