### ISSUE TITLE
execArgv not being interpreted correctly

### ISSUE THREAD

**Issue by bengl** [istanbuljs/nyc#337]
It appears as though when `tap` passes `process.execArgv` params into `nyc`, they aren't being used correctly when spawning.

For example, with a fresh clone of https://github.com/isaacs/node-glob, I ran:

```
$ node --expose-gc node_modules/.bin/tap test/*.js --cov
```

On node 6.3.1, this produces the following error:

```
Error: spawn --expose-gc ENOENT
    at exports._errnoException (util.js:1012:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

Tap sends `process.execArgv` to `nyc` via command-line args [here](https://github.com/tapjs/node-tap/blob/f068025a2b2f49c70b4eefde6ab2511750efed35/bin/run.js#L388-L404).

**Comment by bcoe** [comment]
@bengl what version of nyc are you bumping into this issue on?

**Comment by bengl** [comment]
@bcoe `nyc@6.6.1` and `tap@5.8.0`
