### ISSUE TITLE
Unexpected identifier async ctx => with babel-plugin-istanbul

### ISSUE THREAD

**Issue by ArtworkAD** [istanbuljs/nyc#413]
Hey,

my setup:

```
nodejs v7.0.0-nightly20161004e10516d5a4/   
nyc@v8.3.0 with babel-plugin-istanbul enabled
koa@v2.0.0-alpha.7
```

I am running

`NODE_ENV=test nyc node_modules/jasmine/bin/jasmine.js`

and getting an error at this code

`module.exports.entrypoint = async ctx => {}`

Error (pointing at ctx =>)

```
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:76:16)
    at Object.vm.runInThisContext (/playground/koa/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:141:16)
    at Module._compile (module.js:546:28)
    at Module.replacementCompile (/playground/koa/node_modules/nyc/node_modules/append-transform/index.js:63:13)
    at module.exports (/playground/koa/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/playground/koa/node_modules/nyc/node_modules/append-transform/index.js:67:4)
    at Module.load (module.js:491:32)
    at tryModuleLoad (module.js:450:12)
    at Function.Module._load (module.js:442:3)
    at Module.require (module.js:501:17)

```

**Comment by bcoe** [comment]
@ArtworkAD would it be possible to share the branch of the project that's having issues with us?

**Comment by ArtworkAD** [comment]
@bcoe minimal project to reproduce the issue https://github.com/ArtworkAD/nyc-test I discovered that this issue appears only when using [supertest](https://github.com/visionmedia/supertest) like this:

```
var request = require('supertest').agent(require('../index.js').app.listen());

describe("rest api", function() {
  // empty
});

```
So the problem is not directly related to

`module.exports.entrypoint = async ctx => {}`

**Comment by bySabi** [comment]
@ArtworkAD do you tried?
```
"test": "NODE_ENV=test nyc node --harmony_async_await node_modules/jasmine/bin/jasmine.js
```

**Comment by ArtworkAD** [comment]
@bySabi yeahyyy works. Thank you.
