### ISSUE TITLE
extraneous NaN element in node.getFileCoverage().f in lcov reporter

### ISSUE THREAD

**Issue by jedwards1211** [istanbuljs/nyc#425]
## Expected Behavior

I'm able to create an lcov report with `nyc`

## Observed Behavior

nyc crashes with the following output.  I've only seen this happen with the lcov reporter; the json and text reporters succeed.
```
/Users/andy/crater/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32
        writer.println('FN:' + [meta.decl.start.line, meta.name].join(','));
                                    ^

TypeError: Cannot read property 'decl' of undefined
    at /Users/andy/crater/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:32:37
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (/Users/andy/crater/node_modules/nyc/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at LcovReport.(anonymous function) [as onDetail] (/Users/andy/crater/node_modules/nyc/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail] (/Users/andy/crater/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
...
```

I ran it in the debugger and discovered that the `node` has an extraneous `NaN` element in `node.getFileCoverage().f`, making it 1 element longer than the other corresponding arrays:

![screen shot 2016-10-23 at 4 28 44 pm 1](https://cloud.githubusercontent.com/assets/1448194/19629655/057edc48-993f-11e6-9f7d-d4bd7f32303c.png)

## Bonus Points! Code (or Repository) that Reproduces Issue

Not the minimum repo by any means, but you should be able to reproduce it with:
```sh
git clone git@github.com:jcoreio/crater
cd crater
git checkout coverage
npm install
npm run coverage
```

It's happening on this file:

`crater/src/server/index.js`:
```es6
/* @flow */

import express from 'express'
import path from 'path'
import createSSR from './createSSR'
import { WebApp } from 'meteor/webapp'

import '../universal/collections/Counts'

const app = express()
app.get("/test", (req, res) => res.send("hello world"))
app.get("/test", (req, res) => res.send("hello world"))

app.use((req: Object, res: Object, next: Function) => {
  if (/\/favicon\.?(jpe?g|png|ico|gif)?$/i.test(req.url)) {
    res.status(404).end()
  } else {
    next()
  }
})

if (process.env.NODE_ENV === 'production') {
  app.use('/static', express.static(path.resolve(__dirname, 'static')))
}

// server-side rendering
app.get('*', (req: Object, res: Object, next: Function) => {
  // let Meteor handle sockjs requests so that DDP works
  if (/^\/sockjs/.test(req.path)) {
    next()
    return
  }
  createSSR(req, res)
})

WebApp.rawConnectHandlers.use(app)

console.log(`App is listening on http://0.0.0.0:${process.env.PORT || '80'}`) // eslint-disable-line no-console
```

## Forensic Information

**Operating System:** OS X 10.11.6
**Environment Information:** https://gist.github.com/jedwards1211/7fbeef7cf1294df370e41227df41e94a

**Comment by jedwards1211** [comment]
Actually, I think I know why it's failing; my tests modify `crater/src/server/index.js` to test hot-reloading, and that probably confuses istanbul/nyc.

**Comment by bcoe** [comment]
@jedwards1211 mind giving the `next` release of `nyc` a spin, to make sure this is still an issue:

`npm cache clear; npm i nyc@next`

We just landed a few patches stability patches to istanbul-reports.

**Comment by jedwards1211** [comment]
@bcoe, I just tested, I can still reproduce.  Should I move this to `istanbul-reports`?  I'll see if I can code up a minimum repro case.

**Comment by bcoe** [comment]
@jedwards1211 👍 yes, would love a reproduction in `istanbul-reports`, we can get this patched ASAP.

**Comment by jedwards1211** [comment]
@bcoe sorry for the delay, I finally managed to put together a minimum repro!  Filing in `istanbul-reports` now.

**Comment by Xiphe** [comment]
I stumbled across the same issue in a vue.js project

An answer from @mathieumure helped me find out, that I had my code instrumented twice. Once by babel istanbul plugin, once by jest. (ref (https://github.com/vire/jest-vue-preprocessor/issues/15#issuecomment-313091465)

Though that might not be related to this specific problem, Maybe it helps others who find this issue first.

**Comment by Lange** [comment]
I'm intermittently running into this on [nodecg/nodecg](https://github.com/nodecg/nodecg). As of yet I've not been able to identify the root cause.
