### ISSUE TITLE
When using async/await(enabled by flag `--harmony-async-await`), nyc reports errors.

### ISSUE THREAD

**Issue by dinfer** [istanbuljs/nyc#458]
## Expected Behavior
works with async/await supported by node(using flag `--harmony-async-await`), rather than using babel. 

Even node throws some errors, it also generates a report, which seems right. I don't know how to resolve this problem myself.

## Observed Behavior
When I use node v7 (with node v7 async/await support, not babel) and AVA, it works fine. But running `nyc ava`, it reports errors with very long stack trace.

## Bonus Points! Code (or Repository) that Reproduces Issue
It's a very simple Koa application, some code is listed below.

test/controllers/home.test.js
```js
const test = require('ava')
const {expect} = require('chai')
const request = require('supertest')
const app = require('../../app.js')

test.cb('process', t => {
  request(app.listen())
    .get('/')
    .expect(200, 'Hi', t.end)
})

test.cb('header', t => {
  request(app.listen())
    .get('/')
    .expect(res => {
      expect(res.get('x-time')).to.match(/\d+/)
    })
    .end(t.end)
})
```

controllers/home.js
```js
exports.path = '/'
exports.hello = async function (ctx, next) {
  ctx.body = 'Hi'
}
```

output
```
D:\_\node\template\controllers\home.js:1
(function (exports, require, module, __filename, __dirname) { var cov_h8bezwtjd=function(){var path='D:\\_\\node\\template\\controllers\\home.js',hash='10d7ca573ca5dfd5ca8fe97d98f2191e8db07df5',global=new Function('return th
is')(),gcv='__coverage__',coverageData={path:'D:\\_\\node\\template\\controllers\\home.js',statementMap:{'0':{start:{line:2,column:0},end:{line:2,column:18}},'1':{start:{line:3,column:0},end:{line:5,column:1}},'2':{start:{li
ne:4,column:2},end:{line:4,column:17}}},fnMap:{'0':{name:'(anonymous_0)',decl:{start:{line:3,column:16},end:{line:3,column:17}},loc:{start:{line:3,column:43},end:{line:5,column:1}}}},branchMap:{},s:{'0':0,'1':0,'2':0},f:{'0'
:0},b:{},_coverageSchema:'332fd63041d2c1bcb487cc26dd0d5f7d97098a6c'},coverage=global[gcv]||(global[gcv]={});if(coverage[path]&&coverage[path].hash===hash){return coverage[path];}coverageData.hash=hash;return coverage[path]=c
overageData;}();++cov_h8bezwtjd.s[0];exports.path='/';++cov_h8bezwtjd.s[1];exports.he
SyntaxError: Unexpected token function
    at exports.runInThisContext (vm.js:78:16)
    at Object.vm.runInThisContext (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\istanbul-lib-hook\lib\hook.js:141:16)
    at Module._compile (module.js:543:28)
    at Module.replacementCompile (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:63:13)
    at module.exports (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at extensions.(anonymous function) (D:\_\node\template\node_modules\require-precompiled\index.js:16:3)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at require.extensions.(anonymous function) (D:\_\node\template\node_modules\ava\lib\test-worker.js:92:3)
    at Object.<anonymous> (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at files.filter.forEach.v (D:\_\node\template\controllers\index.js:1:1948)
    at Array.forEach (native)
    at Object.<anonymous> (D:\_\node\template\controllers\index.js:1:1883)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:63:13)
    at module.exports (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at extensions.(anonymous function) (D:\_\node\template\node_modules\require-precompiled\index.js:16:3)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at require.extensions.(anonymous function) (D:\_\node\template\node_modules\ava\lib\test-worker.js:92:3)
    at Object.<anonymous> (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_\node\template\routes.js:1:931)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:63:13)
    at module.exports (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at extensions.(anonymous function) (D:\_\node\template\node_modules\require-precompiled\index.js:16:3)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at require.extensions.(anonymous function) (D:\_\node\template\node_modules\ava\lib\test-worker.js:92:3)
    at Object.<anonymous> (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_\node\template\app.js:1:1134)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:63:13)
    at module.exports (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at extensions.(anonymous function) (D:\_\node\template\node_modules\require-precompiled\index.js:16:3)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at require.extensions.(anonymous function) (D:\_\node\template\node_modules\ava\lib\test-worker.js:92:3)
    at Object.<anonymous> (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_\node\template\test\controllers\home.test.js:5:13)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:63:13)
    at extensions.(anonymous function) (D:\_\node\template\node_modules\require-precompiled\index.js:13:11)
    at C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4
    at require.extensions.(anonymous function) (D:\_\node\template\node_modules\ava\lib\test-worker.js:92:3)
    at Object.<anonymous> (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\_\node\template\node_modules\ava\lib\test-worker.js:96:1)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:63:13)
    at module.exports (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\node_modules\append-transform\index.js:67:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Function.runMain (C:\Users\dinfer\.node-spawn-wrap-11160-e50378a4e788\node:40:10)
    at Object.<anonymous> (C:\Users\dinfer\AppData\Roaming\npm\node_modules\nyc\bin\wrap.js:22:4)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (C:\Users\dinfer\.node-spawn-wrap-11160-e50378a4e788\node:140:8)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
----------------------|----------|----------|----------|----------|----------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------------------|----------|----------|----------|----------|----------------|
All files             |    62.07 |    53.33 |    86.67 |     61.4 |                |
 template             |    33.33 |      100 |        0 |    33.33 |                |
  app.js              |     37.5 |      100 |      100 |     37.5 |    6,7,8,10,14 |
  routes.js           |       25 |      100 |        0 |       25 |        3,35,38 |
 template/controllers |    66.67 |      100 |      100 |    66.67 |                |
  index.js            |    66.67 |      100 |      100 |    66.67 |        9,14,17 |
 template/middlewares |    66.67 |      100 |      100 |    66.67 |                |
  index.js            |    66.67 |      100 |      100 |    66.67 |        9,14,17 |
 template/utils       |    71.43 |    36.36 |       90 |    70.37 |                |
  promiser.js         |    82.35 |       50 |      100 |    81.25 |        7,13,16 |
  validation.js       |    54.55 |    28.57 |       50 |    54.55 | 12,13,15,16,18 |
----------------------|----------|----------|----------|----------|----------------|
```

## Forensic Information

**Operating System:** windows 10 professional (x64 14393.447)
**Environment Information:** [output.txt](https://github.com/istanbuljs/nyc/files/622123/output.txt)

**Comment by bcoe** [comment]
@dinfer I'm trying to reproduce, in testing this works for me:

```
./bin/nyc.js node --harmony-async-await node_modules/.bin/ava test.js 
```

Where `test.js` is:

```js
import test from 'ava';
const foo = require('./foo')

test('foo', t => {
    console.log(foo)
    t.pass();
});
```

and `foo.js` is:

```js
exports.path = '/'
exports.hello = async function (ctx, next) {
  ctx.body = 'Hi'
}
```

Are you using a different approach? Perhaps you could provide a failing example otherwise?

**Comment by dinfer** [comment]
@bcoe Thanks very much
I'm have some work today, I'll provide a failing example after I go home.

**Comment by dinfer** [comment]
Here is the failing project. [the project](https://github.com/dinfer/koa-template)

By the way, projects using babel which translates es6 `async/await` into promise woks fine.

**Comment by dcharbonnier** [comment]
any clue on this problem, same problem with 
` ./node_modules/.bin/nyc node --harmony_async_iteration ./node_modules/mocha/bin/_mocha --opts ./mocha.opts`
