### ISSUE TITLE
ES6 highlighting doesn't seem to work

### ISSUE THREAD

**Issue by djMax** [istanbuljs/nyc#460]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
Coverage and syntax highlighting for ES6/7 should work

## Observed Behavior
When using the instructions in the readme, I get this error:
```
  not ok TypeError: Cannot read property '0' of undefined
    at:
      line: 2
      column: 94
```
 
And

```
(function (exports, require, module, __filename, __dirname) { 'use strict';var cov_qgqkd60q4=function(){var path='/myproject/src/index.js',hash='a704ce2f2b48107e923a407f955207a7cdc67eb9',global=new Function('return this')(),gcv='__coverage__',coverageData={path:'/myproject/src/index.js',statementMap:{'0':{start:{line:3,column:0},end:{line:5,column:3}},'1':{start:{line:6,column:0},end:{line:6,column:99}},'2':{start:{line:8,column:20},end:{line:44,column:3}},'3':{start:{line:9,column:13},end:{line:9,column:66}},'4':{start:{line:10,column:13},end:{line:10,column:55}},'5':{start:{line:11,column:15},end:{line:11,column:44}},'6':{start:{line:12,column:12},end:{line:12,column:26}},'7':{start:{line:13,column:21},end:{line:35,column:3}},'8':{start:{line:36,column:17},end:{line:36,column:50}},'9':{start:{line:38,column:2},end:{line:40,column:3}},'10':{start:{line:39,column:4},end:{line:39,column:26}},'11':{st

TypeError: Cannot read property '0' of undefined
    at _interopRequireDefault (/myproject/src/index.js:1:6093)
    at Object.<anonymous> (/myproject/src/index.js:1:5945)
    at Module._compile (module.js:556:32)
    at Module.replacementCompile (/myproject/node_modules/tap/node_modules/nyc/node_modules/append-transform/index.js:63:13)
    at loader (/myproject/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function) (/myproject/node_modules/babel-register/lib/node.js:154:7)
    at Object.<anonymous> (/myproject/node_modules/tap/node_modules/nyc/node_modules/append-transform/index.js:67:4)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/myproject/tests/test_middleware.js:7:1)
    at Module._compile (module.js:556:32)
    at Module.replacementCompile (/myproject/node_modules/tap/node_modules/nyc/node_modules/append-transform/index.js:63:13)
    at loader (/myproject/node_modules/babel-register/lib/node.js:144:5)```
```

## Forensic Information

**Operating System:** Mac
**Environment Information:**:
node 6.7.0
npm 3.10.3

**Comment by djMax** [comment]
Someone smarter than me suggests this is related to https://github.com/istanbuljs/babel-plugin-istanbul/issues/63

**Comment by bcoe** [comment]
@djMax could you link the repo that is having issues. It would be m good to get to the bottom of this for both you and @kentcdodds

**Comment by kentcdodds** [comment]
That'd be great. Just to be clear, most of the time these days I'm using Jest which will take care of the coverage stuff for me. So I don't currently have this problem anymore.

**Comment by djMax** [comment]
So in trying to get a look-a-like repo to fail I found something moderately interesting, which is that it DIDN'T happen with these deps:

```
"nyc": "^8.3.0",
"tap": "^7.1.2"
```

but did once I switched to 

```
 "tap": "^8.0.1"
```

But I would imagine it's not tap itself blowing it up but a transitive dep. Anyhow, here's the repo:

https://github.com/gas-buddy/hydration

npm run cover should blow it up.

**Comment by djMax** [comment]
A little more info:

Works:
```
└─┬ tap@7.1.2
  └── nyc@7.1.0
```

Doesn't work:
```
└─┬ tap@8.0.1
  └── nyc@9.0.1
```

**Comment by bcoe** [comment]
@kentcdodds what's interesting is I'm pretty sure jest is sharing a bunch of Isanbul components:

https://www.npmjs.com/package/babel-jest
https://github.com/facebook/jest/blob/master/package.json#L21

I would love to get to the bottom of some of these issues because it would help `nyc`, `jest`, and `babel-plugin-istanbul`.

**Comment by bcoe** [comment]
Hey @djMax, not quite sure what's being lost in translation for your -- warrants more digging into. But, when you have babel in the mix, I recommend using `babel-plugin-istanbul` here's updated configuration that worked for me:

**package.json**

```json
{
  "name": "@gasbuddy/hydration",
  "version": "1.0.2",
  "description": "Configuration oriented object construction",
  "main": "build/index.js",
  "scripts": {
    "test": "tap --node-arg=-r --node-arg=babel-register test/*.js",
    "test-some": "tap --node-arg=-r --node-arg=babel-register",
    "cover": "cross-env BABEL_ENV=test nyc tap test/test_*.js",
    "lint": "eslint .",
    "build": "babel src --out-dir build",
    "prepublish": "npm run build"
  },
  "keywords": [
    "gasbuddy",
    "express",
    "serialization",
    "configuration"
  ],
  "author": "GasBuddy",
  "license": "MIT",
  "dependencies": {
    "babel-plugin-transform-object-entries": "^1.0.0"
  },
  "devDependencies": {
    "babel-cli": "^6.16.0",
    "babel-core": "^6.16.0",
    "babel-plugin-istanbul": "^3.0.0",
    "babel-preset-gasbuddy": "^1",
    "babel-register": "^6.16.3",
    "bluebird": "^3.4.6",
    "cross-env": "^3.1.3",
    "eslint": "^3.7.0",
    "eslint-config-gasbuddy": "^1",
    "tap": "^8.0.1"
  },
  "nyc": {
    "lines": 95,
    "statements": 95,
    "functions": 95,
    "branches": 85,
    "include": [
      "src"
    ],
    "require": [
      "babel-register"
    ],
    "sourceMap": false,
    "instrument": false,
    "checkCoverage": true,
    "reporter": [
      "text",
      "lcov"
    ]
  }
}
```

**.babelrc**

```json
{
  "presets": ["gasbuddy"],
  "sourceMaps": true,
  "env": {
    "test": {
      "plugins": [
        [
          "istanbul",
          {
            "exclude": "src/**/*.spec.js"
          }
        ]
      ]
    }
  }
}
```

**Comment by bcoe** [comment]
<img width="522" alt="screen shot 2016-12-02 at 10 34 10 am" src="https://cloud.githubusercontent.com/assets/194609/20845633/e16cf64a-b87a-11e6-8af0-ba3b92e2cfde.png">

@djMax good coverage I might add 💯

**Comment by djMax** [comment]
Hrmph, that did work for me too. babel-plugin-istanbul is/should already be in babel-preset-gasbuddy. I had tried instrument: false before to no avail but perhaps there were multiple issues with the various attempts I made. I'll try this on all the projects and see, but thanks either way.
