### ISSUE TITLE
[Bug] Failed to Write Coverage Reports -- Cannot read property 'start' of undefined 

### ISSUE THREAD

**Issue by patrickml** [istanbuljs/nyc#467]
For some reason we are getting this error when trying to run a coverage report

```sh
Failed to write coverage reports:
        ERROR: TypeError: Cannot read property 'start' of undefined
        STACK: TypeError: Cannot read property 'start' of undefined
    at /Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-reports/lib/lcovonly/index.js:32:42
    at Array.forEach (native)
    at LcovOnlyReport.onDetail (/Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-reports/lib/lcovonly/index.js:30:28)
    at LcovReport.(anonymous function) [as onDetail] (/Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-reports/lib/lcov/index.js:21:24)
    at Visitor.(anonymous function) [as onDetail] (/Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-lib-report/lib/tree.js:34:30)
    at ReportNode.Node.visit (/Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-lib-report/lib/tree.js:123:17)
    at /Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-lib-report/lib/tree.js:116:23
    at Array.forEach (native)
    at visitChildren (/Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-lib-report/lib/tree.js:115:32)
    at ReportNode.Node.visit (/Users/patricklewis/Documents/sites/uTu/console-graphql/node_modules/istanbul-lib-report/lib/tree.js:126:5)
```

The original post was on jest, https://github.com/facebook/jest/issues/2260

**Comment by patrickml** [comment]
Figured out the issue.

We were still using the `__coverage__` plugin prior to switching to jest and this was still in our babel file

```

  "env": {
    "test": {
      "plugins": [ "__coverage__"]
    }
  }
```

**Comment by bcoe** [comment]
@patrickml awesome, I'm glad things are working well now.
