### ISSUE TITLE
Error when trying to inherit other configuration via "extends"

### ISSUE THREAD

**Issue by jooj123** [istanbuljs/nyc#590]
## Expected Behavior

When specifying config like:

```
"nyc": {
    "extends": "@my-group/nyc-config-martin",
    "lines": 0,
    "statements": 0,
    "functions": 0,
    "branches": 0
  }
```

It should use the config specified in `@my-group/nyc-config-martin`

`@my-group/nyc-config-martin` just has a `index.js` export of:

```
module.exports = {
  'check-coverage': true,
  reporter: [
    'html',
    'text',
  ],
  'report-dir': './coverage',
  exclude: [
    'serve/**',
    'src/fixtures/**',
    'test/**',
    'lib/**',
  ],
  cache: true,
};
```

## Observed Behavior

When i try and run i get error:

```
⚠ 1 warning
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/martin/Documents/mr-component/@my-group/nyc-config-martin'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at applyExtends (/Users/martin/Documents/mr-component/node_modules/@my-group/mr-build/node_modules/nyc/node_modules/yargs/lib/apply-extends.js:29:35)
    at Object.Yargs.self.pkgConf (/Users/martin/mr-component/node_modules/@my-group/mr-build/node_modules/nyc/node_modules/yargs/yargs.js:482:14)
    at Object.Config.buildYargs (/Users/martin/Documents/mr-component/node_modules/@mr-group/mr-build/node_modules/nyc/lib/config-util.js:233:6)
    at Object.<anonymous> (/Users/martinjujou/Documents/mr-component/node_modules/@my-group/mr-build/node_modules/nyc/bin/nyc.js:20:49)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

## Forensic Information

**Operating System:** ios el capitan

Possibly the same issue as: https://github.com/istanbuljs/nyc/issues/588 ?

**Comment by jooj123** [comment]
The latest version fixes this

**Comment by bcoe** [comment]
@jooj123 weird! I guess it's something I fixed in an update to yargs?

**Comment by jooj123** [comment]
For some reason i was using version 10 - updating to 11 fixed the issue (this commit: https://github.com/istanbuljs/nyc/commit/a1a457f with the update of `find-up`)
