### ISSUE TITLE
nyc + babel + babel-tap|tape explodes

### ISSUE THREAD

**Issue by krainboltgreene** [istanbuljs/nyc#651]
Alright, so here's the situation:

  - I'm using code that has non-ES5 syntax (transpiled via babel).
  - I'm running tests that have non-ES5 syntax (transpiled via babel).
  - My tests are written in tap format (run via tap OR tape).
  - I want to fail the tests if the coverage doesn't meet standards (100%).

This crossing of babel, tap(e), and nyc seems like it should be a very simple thing, however:

```
| npx nyc babel-tap 'test.js' OR
| npx babel-tap --100 'test.js'
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/krainboltgreene/.node-spawn-wrap-33889-742c35dfb828/babel-node.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Function.Module.runMain (module.js:605:10)
    at Object.<anonymous> (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/babel-cli/lib/_babel-node.js:154:22)
    at Module._compile (module.js:571:32)
    at Module.replacementCompile (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
test.js ............................................... 0/1
  not ok test.js
    timeout: 240000
    file: test.js
    command: >-
      /Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/babel-cli/bin/babel-node.js
    args:
      - test.js
    cwd: /Users/krainboltgreene/Code/unctionjs/mergeRight
    exitCode: 1

total ................................................. 0/1


  0 passing (848.799ms)
  1 failing

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

I figured I would try tape to see if it had a different result:

```
| npx nyc --check-coverage tape -r babel-register test.js
TAP version 13
# Subtest: (unnamed test)
    ok 1 - should be equivalent
    1..1
ok 1 - (unnamed test) # time=4.312ms

# Subtest: (unnamed test)
    ok 1 - should be equivalent
    1..1
ok 2 - (unnamed test) # time=0.974ms

1..2
# time=15.91ms
ERROR: Coverage for lines (81.82%) does not meet global threshold (90%)
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/istanbul-reports/lib/babel-register'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.create (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/node_modules/istanbul-reports/index.js:10:20)
    at /Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/index.js:430:24
    at Array.forEach (native)
    at NYC.report (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/index.js:429:17)
    at report (/Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/bin/nyc.js:89:7)
    at /Users/krainboltgreene/Code/unctionjs/mergeRight/node_modules/nyc/bin/nyc.js:73:27
```

## Forensic Information

https://gist.github.com/krainboltgreene/ae17bc7506e49c1062b83edee950b588

**Comment by krainboltgreene** [comment]
I was actually able to get it working with `NODE_ENV=test` 😊

**Comment by bcoe** [comment]
@krainboltgreene awesome 👍
