### ISSUE TITLE
TypeError: Invalid Version: istanbul-lib-instrument-1.8.0

### ISSUE THREAD

**Issue by sesteva** [istanbuljs/nyc#687]
## Expected Behavior
    "nyc": "^11.2.1",
 Coverage Report after unit tests execution

## Observed Behavior
`> cross-env NODE_ENV=test nyc mocha-webpack

/Users/aaaa/Projects/WebMobile/AppShells/boilerplate-react-redux-webpack/node_modules/nyc/node_modules/semver/semver.js:293
    throw new TypeError('Invalid Version: ' + version);
    ^

TypeError: Invalid Version: https://registry.npmjs.org/istanbul-lib-instrument/-/istanbul-lib-instrument-1.8.0.tgz
    at new SemVer (/Users/aaaa/Projects/WebMobile/AppShells/boilerplate-react-redux-webpack/node_modules/nyc/node_modules/semver/semver.js:293:11)
    at major (/Users/aaaa/Projects/WebMobile/AppShells/boilerplate-react-redux-webpack/node_modules/nyc/node_modules/semver/semver.js:551:10)
    at Object.<anonymous> (/Users/aaaa/Projects/WebMobile/AppShells/boilerplate-react-redux-webpack/node_modules/nyc/node_modules/istanbul-lib-instrument/dist/constants.js:19:117)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)`

## Bonus Points! Code (or Repository) that Reproduces Issue
Running npm test

package.json
   ` "test": "cross-env NODE_ENV=test nyc mocha-webpack",`

.nycrc
`{
   "check-coverage":true,
   "instrument":false,
   "sourceMap":false,
   "reporter":[
      "lcov",
      "text",
      "text-summary"
   ],
   "require":[
      "babel-register"
   ],
   "include":[
      "src/**/*.js"
   ],
   "exclude":[
      "src/routes.js"
   ],
   "all":false,
   "watermarks":{
      "lines":[
         80,
         95
      ],
      "functions":[
         80,
         95
      ],
      "branches":[
         80,
         95
      ],
      "statements":[
         80,
         95
      ]
   }
}
`

## Forensic Information

**Operating System:** OSX 10.11.6
**Environment Information:** 
https://gist.github.com/sesteva/a069468dd28eb0ee2d244264caaed46d

**Comment by sesteva** [comment]
This was actually a problem with package-lock!

**Comment by mateoc10** [comment]
Thanks! I had the same issue, deleted the package-lock and node_modules, then did npm install and worked great
