### ISSUE TITLE
TypeError: ext.toLowerCase is not a function

### ISSUE THREAD

**Issue by starpit** [istanbuljs/nyc#714]
Please use the template provided below, when reporting bugs:
-----

## Expected Behavior
nyc mocha runs without error

## Observed Behavior
```
/../node_modules/nyc/index.js:71
    return ext.toLowerCase()
               ^

TypeError: ext.toLowerCase is not a function
    at /.../node_modules/nyc/index.js:71:16
    at Array.map (<anonymous>)
    at new NYC (/.../node_modules/nyc/index.js:69:62)
    at Object.<anonymous> (/.../node_modules/nyc/bin/nyc.js:36:14)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
```

## Bonus Points! Code (or Repository) that Reproduces Issue
https://travis-ci.org/ibm-functions/shell/jobs/298318311

## Forensic Information

**Operating System:** the operating system you observed the issue on.
both macOS and travis-ubuntu
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.
https://gist.github.com/starpit/eca38d075e8f5cf34600735506e1c16f

**Comment by bcoe** [comment]
@starpit it looks to me like nyc is being loaded with config that has `extensions = true`; reading through your codebase, it looks like you configure nyc programmatically in a few places, I would print out the config at this time, and see what it looks like.

My guess is something like this is somehow happening: `Nyc({extensions: true}).`

**Comment by blimmer** [comment]
fwiw, in my case it was this:

```bash
NODE_ENV=test nyc -reporter=lcov mocha ./tests/test-helper.js --opts ./tests/mocha.opts'
```

(notice the single dash with reporter)

by changing this to `--reporter` it fixed the problem for me

```bash
NODE_ENV=test nyc --reporter=lcov mocha ./tests/test-helper.js --opts ./tests/mocha.opts'
```

**Comment by JaKXz** [comment]
Sounds like this has been solved. If it still doesn't work on the latest version of nyc please open a new issue.
