### ISSUE TITLE
html reporter - cannot view files

### ISSUE THREAD

**Issue by cabezayunke** [istanbuljs/nyc#719]
## Expected behaviour

To be able to navigate and view files

## Actual behaviour

I can navigate through folder and view the % of each level, but when I get to a file and I try to open it I'm getting this:

```
Cannot read property 'start' of undefined 
TypeError: Cannot read property 'start' of undefined
     at /usr/local/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:50:28
     at Array.forEach ()
     at annotateStatements (/usr/local/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:46:33)
     at Object.annotateSourceCode (/usr/local/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/annotator.js:190:9)
     at HtmlReport.onDetail (/usr/local/lib/node_modules/nyc/node_modules/istanbul-reports/lib/html/index.js:217:39)
     at Visitor.(anonymous function) [as onDetail] (/usr/local/lib/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:34:30)
     at ReportNode.Node.visit (/usr/local/lib/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:123:17)
     at /usr/local/lib/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:116:23     at Array.forEach ()
     at visitChildren (/usr/local/lib/node_modules/nyc/node_modules/istanbul-lib-report/lib/tree.js:115:32)

```

## Forensic Information

I've installed nyc globally: ```npm install nyc -g```

and I have this config in .nycrc:

```
{
  "include": [
    "server/"
  ],
  "exclude": [
    "server/docs/"
  ],
  "reporter": [
    "text",
    "html",
    "text-summary"
  ],
  "all": true,
  "check-coverage": true,
  "lines": 80,
  "statements": 80,
  "functions": 80,
  "branches": 80,
  "sourceMap": false,
  "instrument": true
}
```

**Operating System:** MacOS 10.12.6

**Environment Information:** https://gist.github.com/cabezayunke/1ed40af52fa9e6552505dd2f1640a9b6

**Comment by cabezayunke** [comment]
I've also tried installing nyc on the project (npm install nyc --save-dev) and it throws the same error, but it just changes the paths from /usr/local/lib to the project path.

**Comment by bcoe** [comment]
@cabezayunke would you be able to provide a link to the repo having this issue? or a repo with a minimal reproduction?

**Comment by cabezayunke** [comment]
I'll try and create a repo at some point but might take some time... sorry. Also, it seems to work randomly, but 90% of the time still shows that error.

**Comment by JaKXz** [comment]
Closing due to inactivity, please open new issue with a minimal reproduction if you are still seeing issues on the latest version of nyc.
