### ISSUE TITLE
.nyc_output generated as root within Jenkins and Docker

### ISSUE THREAD

**Issue by gCardinal** [istanbuljs/nyc#743]
## Expected Behavior
`.nyc_output` is generated belonging to the Jenkins user

## Observed Behavior
`.nyc_output` is generated, but belongs to `root`

## Forensic Information

**Operating System:** Linux RedHat 3.10.0-693.5.2.el7.x86_64
**Environment Information:** I can't run the given command, but here's some details on the environment:

- The project is all built using Docker and docker-compose
- My Jenkins server is also a Docker container, connecting to it's host's Docker socket via a volume. (I'll paste the `docker-compose.yml` and `Dockerfile` at the end of this issue)
- I try and run the following command as part of my Jenkins task: `nyc mocha-webpack --webpack-config config/webpack/webpack.config.test.js --require react/tests/bootstrap.js --glob *.test.ts* --recursive react/tests`

Now, my task clones the project and then generates the workspace, I spin up Docker containers for PHP, mySQL and Node and run my tests to ensure I can deploy. Part of that flow means running the above `nyc mocha-webpack` command. For some reason, `.nyc_output` belongs to root when that's ran and I get an error since my Jenkins user does not have access to the folder (for obvious reasons).

The error:
```
internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1021:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at ChildProcess.wrappedSpawn [as spawn] (/app/node_modules/nyc/node_modules/spawn-wrap/index.js:84:15)
    at exports.spawn (child_process.js:494:9)
    at module.exports (/app/node_modules/nyc/node_modules/foreground-child/index.js:39:15)
    at Object.<anonymous> (/app/node_modules/nyc/bin/nyc.js:63:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
```

The generated workspace:

```
[devdocker@trdxjkns1 tests]$ ls -la
total 300
drwxr-xr-x.  17 devdocker devdocker   4096 Dec  8 11:34 .
drwxr-xr-x.   6 devdocker devdocker     88 Dec  8 11:32 ..
drwxr-xr-x.   2 devdocker devdocker     45 Dec  8 11:34 acquia-utils
-rw-r--r--.   1 devdocker devdocker     48 Dec  8 11:34 .bablerc
drwxr-xr-x.   4 devdocker devdocker    223 Dec  8 11:34 bin
drwxr-xr-x.   9 devdocker devdocker    119 Dec  8 11:34 config
drwxr-xr-x.   4 devdocker devdocker     46 Dec  8 11:34 content
drwxr-xr-x.   5 devdocker devdocker    200 Dec  8 11:34 docker
drwxr-xr-x.  10 devdocker devdocker   4096 Dec  8 11:34 docroot
drwxr-xr-x.   8 devdocker devdocker    162 Dec  8 11:34 .git
-rw-r--r--.   1 devdocker devdocker    413 Dec  8 11:34 .gitignore
drwxr-xr-x.   3 devdocker devdocker     20 Dec  8 11:34 hooks
drwxr-xr-x.   2 devdocker devdocker     21 Dec  8 11:34 .idea
drwxr-xr-x.   2 devdocker devdocker     30 Dec  8 11:34 key
drwxr-xr-x.   2 devdocker devdocker     24 Dec  8 11:34 library
drwxr-xr-x. 842 devdocker devdocker  24576 Dec  8 11:34 node_modules
drwxr-xr-x.   2 root      root          51 Dec  8 11:34 .nyc_output
-rw-r--r--.   1 devdocker devdocker    483 Dec  8 11:34 .nycrc
-rw-r--r--.   1 devdocker devdocker   2544 Dec  8 11:34 package.json
drwxr-xr-x.   4 devdocker devdocker     47 Dec  8 11:34 react
-rw-r--r--.   1 devdocker devdocker    567 Dec  8 11:34 README.acquia
-rw-r--r--.   1 devdocker devdocker   7337 Dec  8 11:34 README.md
-rw-r--r--.   1 devdocker devdocker    608 Dec  8 11:34 tsconfig.json
-rw-r--r--.   1 devdocker devdocker     87 Dec  8 11:34 tsconfig.test.json
-rw-r--r--.   1 devdocker devdocker    555 Dec  8 11:34 tslint.json
drwxr-xr-x.   2 devdocker devdocker     27 Dec  8 11:34 .vscode
-rw-r--r--.   1 devdocker devdocker    512 Dec  8 11:34 .yarnclean
-rw-r--r--.   1 devdocker devdocker 212863 Dec  8 11:34 yarn.lock
```

The `docker-compose.yml` file used to spin up the Jenkins running the above:
```
version: '2'

services:
  jenkins:
    restart: always
    user: "1002"
    build:
      context: ./jenkins
    ports:
      - "9002:8080"
      - "50002:50000"
    volumes:
      - ../jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/var/.ssh
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

```

The `Dockerfile` of the Jenkins instance, allowing it to connect to the Docker socket:
```
FROM jenkins/jenkins

ARG JENKINS_HOME_REF=/usr/share/jenkins/ref
ARG USER_ID=1002
ARG USER_GROUP_ID=1002
ARG DOCKER_GROUP_ID=777

# Switch to root for the next few operations
USER root

RUN apt-get clean
RUN apt-get update \
    && apt-get install -y  \
        sudo \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common

# Add Jenkins user to sudoers so it can launch Docker containers
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

# Install Docker
RUN curl -sSL https://get.docker.com/ | sh

# Install Docker Compose
RUN curl -L https://github.com/docker/compose/releases/download/1.15.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose

# Add Jenkins to the docker group so it can run Docker commands
RUN usermod -a -G docker jenkins
# Change the uid of the Jenkins user so that it's the same as devdocker
RUN usermod -u ${USER_ID} jenkins
# Change the group to reflect devdocker's
RUN groupmod -g ${USER_GROUP_ID} jenkins
# Change the docker group's ID. If the ID is different, connection to the socket will not be permited
RUN groupmod -g ${DOCKER_GROUP_ID} docker

# Copy required files to the directory Jenkins will use as it's base to build jenkins_home/
# Plugins
COPY plugins.txt ${JENKINS_HOME_REF}/plugins.txt

# Custom configuration
COPY config.xml ${JENKINS_HOME_REF}/config.xml

# Groovy scripts
COPY add-global-environment-variables.groovy ${JENKINS_HOME_REF}/init.groovy.d/

# Fix permissions (those files will belong to root)
RUN chown -R ${USER_ID}:${USER_ID} ${JENKINS_HOME_REF}
RUN chmod -R 744 ${JENKINS_HOME_REF}
RUN chown -R ${USER_ID}:${USER_ID} /var/jenkins_home
RUN chmod -R 744 /var/jenkins_home

# Returns to jenkins user (otherwise the jenkins_home is unusable due to belonging to root)
USER jenkins

# Install plugins
RUN /usr/local/bin/install-plugins.sh < ${JENKINS_HOME_REF}/plugins.txt
```

**Comment by bcoe** [comment]
@gCardinal the `.nyc_output` directory is created using the library `mkdirp`:

`mkdirp.sync(this.tempDirectory())`

perhaps check if `mkdirp` is creating folders with inappropriate permissions in general? at which point it might be worth opening an issue in the upstream project.

**Comment by slatunje** [comment]
I am facing the exact same issue as described above.
@gCardinal did you ever resolve this?

**Comment by gCardinal** [comment]
Sadly no, we were rushed for time in the project I'm working on and I had to simply drop code coverage in general.

Time is not my friend these days, but if I can get an hour, I'll give it a look.

**Comment by slatunje** [comment]
@gCardinal thanks

tell app to create its own temp directory outside of its root directory and let `nyc` know where the root directory is.

now jenkins has permission to job

package.json
```json
{
  "scripts": {
    "setup": "mkdir -p /tmp/.nyc_output/",
    "unit": "NODE_PATH=. BABEL_ENV=test node node_modules/.bin/nyc ava ./test/*.spec.js"
  }
}
```

nycrc
```json
{
  "include": [],
  "extension": [],
  "reporter": [],
  "temp-directory": "/tmp/.nyc_output"
}

```

    yarn setup
    yarn unit

**Comment by Trendy** [comment]
I'm running into this issue locally as well. As far as I can tell the output directory isn't being generated as root, but I get a similar error:
```
> . ./config/test-ci.sh && ./node_modules/.bin/nyc ./spec/support/runner.js

internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at ChildProcess.wrappedSpawn [as spawn] (/Users/trendy/dev/icm-email-analytics-api/node_modules/nyc/node_modules/spawn-wrap/index.js:91:15)
    at exports.spawn (child_process.js:502:9)
    at module.exports (/Users/trendy/dev/icm-email-analytics-api/node_modules/nyc/node_modules/foreground-child/index.js:39:15)
    at Object.<anonymous> (/Users/trendy/dev/icm-email-analytics-api/node_modules/nyc/bin/nyc.js:63:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! Test failed.  See above for more details.
```
```
trendy$ ls -al
...
-rw-r--r--    1 trendy  staff    1057 May  4 14:27 .gitignore
drwxr-xr-x    2 trendy  staff      64 Sep 10 15:02 .nyc_output
-rw-r--r--    1 trendy  staff     344 Jun 26 13:41 .sequelizerc
...
```

**Comment by carlnordenfelt** [comment]
I'm seeing the same issue, local.
Seems there are more issues on this topic: #737 #871 
    
    "scripts": {
        "test:unit": "LOG_LEVEL=suppress nyc --all --include src/**/*.js node_modules/.bin/_mocha ./tests/unit --recursive && npm run report",
        "report": "nyc report --reporter=html"
    },

Directories:

    drwxr-xr-x    3 user  staff      96 13 Feb 09:21 .nyc_output

**Comment by doublesharp** [comment]
I'm still using the `istanbul` cli so my output folder is `./coverage` but I was able to make it work by creating the directory first as the `jenkins` user with `mkdir -p ./coverage` then running the `docker-compose run` (not build) as the jenkins user/group with `-u $(id -u):$(id -g)` and mounting the output volume with an absolute path `-v $(pwd)/coverage:/app/coverage` (where my `Dockerfile` loads into `/app`).

```
# needed to set permissions
mkdir -p ./coverage

# build the latest
docker-compose build

# use `run` to specify -u and -v mounts (must be absolute path)
docker-compose \
  run \
  -u $(id -u):$(id -g) \
  -v $(pwd)/coverage:/app/coverage \
  --rm \
  service \
  npm run coverage

# stop everything
docker-compose down
```

The resulting coverage folder in my workspace job directory as well as the subdirectories and files are owned by `jenkins:jenkins`.

```
[root@jenkins-server /]# ls -la /var/lib/jenkins/workspace/app-build/coverage/
total 1748
drwxr-xr-x  3 jenkins jenkins   4096 Mar 26 09:43 .
drwxr-xr-x 16 jenkins jenkins   4096 Mar 26 09:43 ..
-rw-r--r--  1 jenkins jenkins 562152 Mar 26 09:43 cobertura-coverage.xml
-rw-r--r--  1 jenkins jenkins 991913 Mar 26 09:43 coverage.raw.json
-rw-r--r--  1 jenkins jenkins 143085 Mar 26 09:43 lcov.info
drwxr-xr-x  3 jenkins jenkins   4096 Mar 26 09:43 lcov-report
-rwxr-xr-x  1 jenkins jenkins  69598 Mar 26 09:43 xunit.xml
```

**Comment by coreyfarrell** [comment]
I'm not sure this is an issue with nyc.  nyc does not control what user:group owns files/folders it creates, the OS decides what the ownership should be based on the user:group which is running nyc.

I suspect this is an issue with the setup, maybe some commands are being run under an unexpected username?

@doublesharp FYI `istanbul` CLI command is not part of nyc.  That is the predecessor to nyc, it is unmaintained.

**Comment by coreyfarrell** [comment]
As I pointed out nyc creates files as whatever the current user is so I don't think this is an nyc bug.  If anyone is still experiencing this issue with the current version of nyc please link a repository which demonstrates the issue and I can reopen this issue.
