### ISSUE TITLE
Command always fails after first run

### ISSUE THREAD

**Issue by mojavelinux** [istanbuljs/nyc#749]
## Expected Behavior

I should be able to run the `nyc` consecutively and get the same outcome each time.

## Observed Behavior

The second time I run the `nyc` command (wrapping mocha), the command fails.

Here's the command I'm using:

```
./node_modules/.bin/nyc ./node_modules/.bin/_mocha packages/*/test/*-test.js
```

Here's the error I'm getting (after the first run, which succeeds):

```
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at runInThisContext (vm.js:139:10)
    at Object.vm.runInThisContext (/tmp/antora/node_modules/nyc/node_modules/istanbul-lib-hook/lib/hook.js:142:16)
    at Module._compile (module.js:599:28)
...
```

If I remove *node_modules* and run `yarn` again, then the command succeeds the next time I run it, but fails again the time after that.

## Code (or Repository) that Reproduces Issue

https://gitlab.com/opendevise/oss/antora (branch nyc-issue-749)

```
git clone -b nyc-issue-749 https://gitlab.com/opendevise/oss/antora.git
```

Use `yarn` to install dependencies.

(ignore the Gulp build)

## Forensic Information

**Operating System:** Fedora 26
**Environment Information:** 

Node 8.9.3
yarn 1.3.2

**Comment by mojavelinux** [comment]
It's worth noting the deprecated istanbul 1.1.0-alpha.1 works on the exact same repository with no issue.

**Comment by mojavelinux** [comment]
I finally figured out that the problem is with files in the cache. I didn't realize nyc was writing files to a cache folder, nor did I know how to find it, until I discovered the `--cache-dir` flag.

If I set the `--cache-dir` to a local folder, then remove it between tests, then `nyc` always succeeds.

Is no one else seeing this issue?

**Comment by mojavelinux** [comment]
And I've now discovered the `--cache` flag, which allows me to disable the cache. If I disable the cache, the command finishes successfully on every run.

I have a sneaking suspicion that the problem is with Opal generated code, which my project uses. I'll try to reproduce the scenario in a more isolated test so that we can pinpoint the problem.

**Comment by mojavelinux** [comment]
I think I've figured out the problem, I just can't explain why it's happening.

When I use a library compiled with Opal in my project, the transformed code ends up with `\u0000` before every character. If I update the wrapCustomHook function of append-transform as follows, then it works:

```js
module._compile = function replacementCompile(code, filename) {
    module._compile = originalCompile;
    code = transform(code, filename);
    try {
        module._compile(code, filename);
    } catch (e) {
        module._compile(code.replace(/\u0000/g, ''), filename); 
    }
};
```

I have no idea why the `\u0000` characters are getting added to the code, but that's what's breaking the cache.

**Comment by mojavelinux** [comment]
It does appear the files are written in the cache this way, so the problem is with the caching writer.

**Comment by mojavelinux** [comment]
These are null characters. When I view the file, I can remove them in vim using:

```
%s/\%x00//g
```

**Comment by mojavelinux** [comment]
It would appear that the problem is actually on the following line in write-file-atomic:

https://github.com/npm/write-file-atomic/blob/1597785cb9e1152056d905a357b3891b3295506d/index.js#L184

It's wrapping the encoding in `String()`, which somehow confuses the node into writing the file with UTF-16LE.

**Comment by mojavelinux** [comment]
Okay, I've got it. The problem is that Opal overrides the `encoding` property on a String, which is confusing write-file-atomic. Consider this code:

```
const Opal = require('opal-runtime').Opal

console.log('utf8'.encoding)

$Encoding {
  '$$id': 190,
  name: 'UTF-16LE',
  names: [ 'UTF-16LE' ],
  ascii: false,
  dummy: false }
```

So when write-file-atomic calls this line:

```
String(options.encoding || 'utf8')
```

The result is UTF16-LE. Now we know why we get cache files that can't be read back in.

**Comment by mojavelinux** [comment]
Technically, I think write-file-atomic should be careful about checking whether options is already a string and only call the encoding property if it's not. (But yes, I agree Opal is doing stuff here it really shouldn't be doing too).

**Comment by mojavelinux** [comment]
Here's the workaround for this when using Opal. Add this line immediately after requiring Opal anywhere:

```
String.prototype.encoding = Opal.const_get_local(Opal.const_get_qualified('::', 'Encoding'), 'UTF_8')
```

Here's a related issue in Opal. https://github.com/opal/opal/issues/1401

**Comment by mojavelinux** [comment]
I don't see how this is an issue with nyc, so I'm happy to close the issue and pursue the problem elsewhere.
