### ISSUE TITLE
Cannot find module '-s'

### ISSUE THREAD

**Issue by splincode** [istanbuljs/nyc#751]
package.json

```
{
  "name": "@splincode/client-logger",
  "version": "0.0.31",
  "description": "Simple logger for browser",
  "main": "dist/logger.js",
  "typings": "dist/logger",
  "scripts": {
    "test": "nyc mocha",
    "compile": "ts-node src/logger.ts",
    "prepublishOnly": "tsc"
  },
  "nyc": {
    "include": [
      "src/**/*.ts"
    ],
    "extension": [
      ".ts"
    ],
    "require": [
      "ts-node/register"
    ],
    "reporter": [
      "text-summary",
      "html"
    ],
    "sourceMap": true,
    "instrument": true
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/splincodewd/client-logger.git"
  },
  "keywords": [
    "console",
    "logger",
    "javascript",
    "browser",
    "typescript"
  ],
  "author": "splincodewd",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/splincodewd/client-logger/issues"
  },
  "homepage": "https://github.com/splincodewd/client-logger#readme",
  "devDependencies": {
    "@types/chai": "^4.0.8",
    "@types/jasmine": "^2.8.2",
    "@types/mocha": "^2.2.44",
    "chai": "^4.1.2",
    "mocha": "^4.0.1",
    "nyc": "^11.3.0",
    "source-map-support": "^0.5.0",
    "ts-node": "^4.0.1",
    "typescript": "^2.6.2",
    "typings": "^2.1.1"
  }
}
```

```
> @splincode/client-logger@0.0.31 test C:\Users\splincode\Desktop\dev\logger
> nyc mocha

Error: Cannot find module '-s'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at C:\Users\splincode\Desktop\dev\logger\node_modules\mocha\bin\_mocha:370:3
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\splincode\Desktop\dev\logger\node_modules\mocha\bin\_mocha:369:10)
    at Module._compile (module.js:624:30)
    at Module.replacementCompile (C:\Users\splincode\Desktop\dev\logger\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at module.exports (C:\Users\splincode\Desktop\dev\logger\node_modules\nyc\node_modules\default-require-extensions\js.js:8:9)
    at Object.<anonymous> (C:\Users\splincode\Desktop\dev\logger\node_modules\nyc\node_modules\append-transform\index.js:62:4)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at runMain (C:\Users\splincode\.node-spawn-wrap-18844-904ffcaa34e3\node:68:10)
    at Function.<anonymous> (C:\Users\splincode\.node-spawn-wrap-18844-904ffcaa34e3\node:171:5)
    at Object.<anonymous> (C:\Users\splincode\Desktop\dev\logger\node_modules\nyc\bin\wrap.js:23:4)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at C:\Users\splincode\.node-spawn-wrap-18844-904ffcaa34e3\node:178:8
    at Object.<anonymous> (C:\Users\splincode\.node-spawn-wrap-18844-904ffcaa34e3\node:181:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

=============================== Coverage summary ===============================
Statements   : Unknown% ( 0/0 )
Branches     : Unknown% ( 0/0 )
Functions    : Unknown% ( 0/0 )
Lines        : Unknown% ( 0/0 )
================================================================================
npm ERR! Test failed.  See above for more details.

```

**Comment by bcoe** [comment]
@splincode could you provide a link to a repo that reproduces this issue? I'm curious to see if the issue happens on both Windows and Linux systems.

**Comment by bcoe** [comment]
@splincode curious, what was the underlying issue?

**Comment by splincode** [comment]
I could not figure it out, in the end I could not reproduce it now, because I deleted the repository

**Comment by KobbyMmo** [comment]
i am having this error. This is a link to the repo [node-gae-env](https://github.com/KobbyMmo/node-gae-env/tree/dev)
