### ISSUE TITLE
Cannot find module 'brace-expansion'

### ISSUE THREAD

**Issue by fishcharlie** [istanbuljs/nyc#819]
## General

I'm getting the following error when trying to run the CI tests. It looks like this could be an issue with `nyc` due to that being the start of the stack trace, but there are also reasons why I believe that it could be an issue with another system, if so please let me know your thoughts so I can try to chase down a solution.

## Expected Behavior

I expect `nyc` to be able to run correctly and be able to access all dependencies.

## Observed Behavior

```
Error: Cannot find module 'brace-expansion'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/automategreen/dynamoose/node_modules/minimatch/minimatch.js:10:14)
    at Module._compile (module.js:652:30)
    at Module.replacementCompile (/home/travis/build/automategreen/dynamoose/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/home/travis/build/automategreen/dynamoose/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/home/travis/build/automategreen/dynamoose/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:565:32)
```

## Bonus Points! Code (or Repository) that Reproduces Issue

[Travis CI build](https://travis-ci.org/automategreen/dynamoose/jobs/369217391)
[GitHub Repo](https://github.com/automategreen/dynamoose/pull/347)

## Other Notes

This only seems to be breaking on Node.js version >= 8 and NPM >= 5.4.

**Comment by bcoe** [comment]
@fishcharlie doing some initial testing, the `package-lock.json` seems to be somewhat broken. Perhaps try by deleting `package-lock.json`, nuking `node_modules`, and re-installing?

**Comment by fishcharlie** [comment]
Looks like this worked. Thanks **SO** much @bcoe. And thank you for all your work on this project.
