### ISSUE TITLE
Running nyc on a FIPS enabled system fails due to use of weak md5 algorithm.

### ISSUE THREAD

**Issue by kresss** [istanbuljs/nyc#869]
## Expected Behavior
nyc should work on FIPS enabled systems.

## Observed Behavior
nyc fails.

```
$ ./node_modules/.bin/nyc ./node_modules/.bin/mocha "test/init-test-env.js" "test/unit/**/*.js"
crypto.js:81
  this._handle = new binding.Hash(algorithm);

Error: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
    at new Hash (crypto.js:81:18)
    at Object.createHash (crypto.js:611:10)
    at module.exports (/home/kresss/GIT/wsm/mcs/node_modules/nyc/node_modules/md5-hex/index.js:5:20)
    at NYC.generateUniqueID (/home/kresss/GIT/wsm/mcs/node_modules/nyc/index.js:373:10)
    at new NYC (/home/kresss/GIT/wsm/mcs/node_modules/nyc/index.js:88:47)
    at Object.<anonymous> (/home/kresss/GIT/wsm/mcs/node_modules/nyc/bin/nyc.js:36:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
```

## Forensic Information

RHEL 7.5 with FIPS enabled at the kernel level. 
Node v8.9.4
npm v5.6.0

**Comment by kresss** [comment]
I made an attempt at fixing this. See #870
