### ISSUE TITLE
"Error: spawn EACCES" on travis

### ISSUE THREAD

**Issue by kslhunter** [istanbuljs/nyc#871]
package.json

```
"scripts": {
    "test": "rimraf .nyc_output coverage && concurrently \"yarn test:core\" \"yarn test:orm-query\" \"yarn test:orm-connector\" \"yarn test:socket\"",
    "build": "yarn build:core && concurrently \"yarn build:orm-query\" \"yarn build:orm-connector\" \"yarn build:socket-common\" && concurrently \"yarn build:socket-server\" \"yarn build:socket-client\"",
    "--": "",
    "test+build": "yarn test && yarn build",
    "-- ": "",
    "test:core": "rimraf coverage/core .nyc_output/core && cross-env TS_NODE_PROJECT=tests/core/tsconfig.json nyc --report-dir coverage/core --temp-directory .nyc_output/core --include packages/core/src/** --reporter html --reporter text --extension .ts mocha --require ts-node/register --require tsconfig-paths/register tests/core/**/*.spec.ts",
    "test:orm-query": "rimraf coverage/orm-query .nyc_output/orm-query && cross-env TS_NODE_PROJECT=tests/orm-query/tsconfig.json nyc --report-dir coverage/orm-query --temp-directory .nyc_output/orm-query --include packages/orm-query/src/** --reporter html --reporter text --extension .ts mocha --require ts-node/register --require tsconfig-paths/register tests/orm-query/**/*.spec.ts",
    "test:orm-connector": "rimraf coverage/orm-connector .nyc_output/orm-connector && cross-env TS_NODE_PROJECT=tests/orm-connector/tsconfig.json nyc --report-dir coverage/orm-connector --temp-directory .nyc_output/orm-connector --include packages/orm-connector/src/** --reporter html --reporter text --extension .ts mocha --require ts-node/register --require tsconfig-paths/register tests/orm-connector/**/*.spec.ts",
    "test:socket": "rimraf coverage/socket .nyc_output/socket && cross-env TS_NODE_PROJECT=tests/socket/tsconfig.json nyc --report-dir coverage/socket --temp-directory .nyc_output/socket --include packages/socket-client/src/** --include packages/socket-server/src/** --include packages/socket-common/src/** --reporter html --reporter text --extension .ts mocha --require ts-node/register --require tsconfig-paths/register tests/socket/**/*.spec.ts",
    "--  ": "",
    "build:core": "tslint -c packages/core/tslint.json -p packages/core/tsconfig-build.json -t msbuild && rimraf packages/core/dist && tsc --project packages/core/tsconfig-build.json",
    "build:orm-query": "tslint -c packages/orm-query/tslint.json -p packages/orm-query/tsconfig-build.json -t msbuild && rimraf packages/orm-query/dist && tsc --project packages/orm-query/tsconfig-build.json",
    "build:orm-connector": "tslint -c packages/orm-connector/tslint.json -p packages/orm-connector/tsconfig-build.json -t msbuild && rimraf packages/orm-connector/dist && tsc --project packages/orm-connector/tsconfig-build.json",
    "build:socket-common": "tslint -c packages/socket-common/tslint.json -p packages/socket-common/tsconfig-build.json -t msbuild && rimraf packages/socket-common/dist && tsc --project packages/socket-common/tsconfig-build.json",
    "build:socket-server": "tslint -c packages/socket-server/tslint.json -p packages/socket-server/tsconfig-build.json -t msbuild && rimraf packages/socket-server/dist && tsc --project packages/socket-server/tsconfig-build.json",
    "build:socket-client": "tslint -c packages/socket-client/tslint.json -p packages/socket-client/tsconfig-build.json -t msbuild && rimraf packages/socket-client/dist && tsc --project packages/socket-client/tsconfig-build.json"
  },
  "devDependencies": {
    "@types/core-js": "^2.5.0",
    "@types/jsdom": "^11.0.6",
    "@types/mime": "^2.0.0",
    "@types/mocha": "^5.2.2",
    "@types/node": "^10.3.4",
    "@types/sinon": "^5.0.1",
    "@types/tedious": "^1.8.33",
    "@types/ws": "^5.1.2",
    "bufferutil": "^3.0.5",
    "concurrently": "^3.6.0",
    "core-js": "^2.5.7",
    "cross-env": "^5.2.0",
    "jsdom": "^11.11.0",
    "mime": "^2.3.1",
    "mocha": "^5.2.0",
    "nyc": "^12.0.2",
    "sinon": "^6.0.1",
    "tedious": "^2.6.1",
    "ts-node": "^6.1.1",
    "tsconfig-paths": "^3.4.0",
    "tslint": "^5.10.0",
    "tslint-language-service": "^0.9.9",
    "typescript": "^2.9.2",
    "utf-8-validate": "^4.0.2",
    "ws": "^5.2.1"
  }
```

travis output

```
[0] $ rimraf coverage/core .nyc_output/core && cross-env TS_NODE_PROJECT=tests/core/tsconfig.json nyc --require ts-node/register --report-dir coverage/core --temp-directory .nyc_output/core --include packages/core/src/** --reporter html --reporter text --extension .ts mocha --require tsconfig-paths/register tests/core/**/*.spec.ts
[3] $ rimraf coverage/socket .nyc_output/socket && cross-env TS_NODE_PROJECT=tests/socket/tsconfig.json nyc --require ts-node/register --report-dir coverage/socket --temp-directory .nyc_output/socket --include packages/socket-client/src/** --include packages/socket-server/src/** --include packages/socket-common/src/** --reporter html --reporter text --extension .ts mocha --require tsconfig-paths/register tests/socket/**/*.spec.ts
[2] $ rimraf coverage/orm-connector .nyc_output/orm-connector && cross-env TS_NODE_PROJECT=tests/orm-connector/tsconfig.json nyc --require ts-node/register --report-dir coverage/orm-connector --temp-directory .nyc_output/orm-connector --include packages/orm-connector/src/** --reporter html --reporter text --extension .ts mocha --require tsconfig-paths/register tests/orm-connector/**/*.spec.ts
[1] $ rimraf coverage/orm-query .nyc_output/orm-query && cross-env TS_NODE_PROJECT=tests/orm-query/tsconfig.json nyc --require ts-node/register --report-dir coverage/orm-query --temp-directory .nyc_output/orm-query --include packages/orm-query/src/** --reporter html --reporter text --extension .ts mocha --require tsconfig-paths/register tests/orm-query/**/*.spec.ts
[3] internal/child_process.js:323
[3]     throw errnoException(err, 'spawn');
[3]     ^
[3] 
[3] Error: spawn EACCES
[3]     at _errnoException (util.js:992:11)
[3]     at ChildProcess.spawn (internal/child_process.js:323:11)
[3]     at ChildProcess.wrappedSpawn [as spawn] (/home/travis/build/kslhunter/simplism8/node_modules/nyc/node_modules/spawn-wrap/index.js:91:15)
[3]     at exports.spawn (child_process.js:502:9)
[3]     at module.exports (/home/travis/build/kslhunter/simplism8/node_modules/nyc/node_modules/foreground-child/index.js:39:15)
[3]     at Object.<anonymous> (/home/travis/build/kslhunter/simplism8/node_modules/nyc/bin/nyc.js:63:3)
[3]     at Module._compile (module.js:652:30)
[3]     at Object.Module._extensions..js (module.js:663:10)
[3]     at Module.load (module.js:565:32)
[3]     at tryModuleLoad (module.js:505:12)
[3] error Command failed with exit code 1.
[3] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[3] yarn test:socket exited with code 1
[1] internal/child_process.js:323
[1]     throw errnoException(err, 'spawn');
[1]     ^
```

.travis.yml
```
sudo: required
language: node_js
cache: yarn
node_js:
  - "8"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH
install: yarn
script:
  - yarn test+build
```

## Expected Behavior
No errors

## Bonus Points! Code (or Repository) that Reproduces Issue
travis: https://travis-ci.org/kslhunter/simplism8
github: https://github.com/kslhunter/simplism8

## Forensic Information

**Operating System:** the operating system you observed the issue on.
**Environment Information:** information about your project's environment, see instructions below:

1. run the following script:

sh -c 'node --version; npm --version; npm ls' > output.txt

2. share a gist with the contents of output.txt.

**Comment by coreyfarrell** [comment]
Has this only happened on travis or does it happen locally?  If it happens locally how do I reproduce the issue?  `yarn install && yarn test`?
