### ISSUE TITLE
Feature Request: nyc report should be able to take a list of --temp-directory

### ISSUE THREAD

**Issue by osher** [istanbuljs/nyc#879]
Consider the following usage:
```
nyc --all -n bin --show-process-tree --temp-directory coverage/unit1 mocha -b test/unit1/**.test.js
nyc --all -n bin --show-process-tree --temp-directory coverage/unit2 mocha -b test/unit2/**.test.js
nyc report --temp-directory coverage/unit1  --temp-directory coverage/unit2 -r lcov
``` 
Expect - `nyc` read from all temp-dirs and produce a report.

Current behavior - 

```
C:\ws\node_modules\nyc\node_modules\yargs\yargs.js:1133
      else throw err
           ^

TypeError: Path must be a string. Received [ 'coverage\\unit1', 'coverage\\unit2' ]
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:221:7)
    at NYC.tempDirectory (C:\ws\\node_modules\nyc\index.js:562:15)
    at NYC.eachReport (C:\ws\\node_modules\nyc\index.js:524:41)
    at NYC.getCoverageMapFromAllCoverageFiles (C:\file-svr\node_modules\nyc\index.js:432:8)
    at NYC.report (C:\ws\node_modules\nyc\index.js:450:18)
    at Object.exports.handler (C:\ws\node_modules\nyc\lib\commands\report.js:44:7)
    at Object.runCommand (C:\ws\node_modules\nyc\node_modules\yargs\lib\command.js:235:44)
    at Object.parseArgs [as _parseArgs] (C:\ws\node_modules\nyc\node_modules\yargs\yargs.js:1046:30)
    at Object.parse (C:\ws\node_modules\nyc\node_modules\yargs\yargs.js:551:25)
```

which is a pitty.

**Comment by osher** [comment]
You may also decide to allow `--temp-directory` provided to `report` to accept glob-patterns - which would be totally awesome!

**Comment by AndrewFinlay** [comment]
Not sure if you're having trouble or if this is just a FR for convenience.  This functionality is pretty easily achieved by copying the coverage results from e2e and unit tests to a common directory, then running the reporting tool on that.

**Comment by osher** [comment]
I made this PR because I believe the abilities of this team and am convinced by the level of usability the team is aiming for 👍 

After all - it's a rather common practice to run a tool in e2e mode with different settings.
(my example above is a simplification of a long list of e2e cases my SUT cli tool is required to support)

I agree that the proposed workaround would work - but it's a work around.
If you chose to reject it - I'll be disappointed, but I'll understand....

**Comment by osher** [comment]
P.S - how about providing a `glob` pattern in `--temp-directory` ?

**Comment by AndrewFinlay** [comment]
Hi Osher, I'm not a maintainer so I won't be making any decisions on whether to develop this functionality, but for what it's worth I think that functionality would be helpful.  My point is that you can achieve the same result now using shell commands, if that helps you or someone else then that's great.

**Comment by osher** [comment]
@AndrewFinlay  - evidently, point taken. Let leave the ball on the maintainers court.
If I had a little window I might have PR it myself, but this will have to wait

**Comment by JaKXz** [comment]
@coreyfarrell @AndrewFinlay thoughts on this? 

@osher would you be willing to take a crack at that PR with tests? :)

**Comment by AndrewFinlay** [comment]
It makes sense, and probably wouldn't be too hard to add.  I'll wait to see if @osher is keen to tackle this before I throw my hat in the ring.

**Comment by coreyfarrell** [comment]
A few thoughts:
1. The main nyc command needs to report a proper error if `--temp-dir` is specified multiple times as this is impossible.  Unfortunately I don't see a way to instruct `yargs` to throw an error for this.
2. I'm good with supporting multiple `--temp-dir` paths for `nyc report`.  This will need testing (probably create a two subdirs in fixtures with pre-populated coverage.json in each, verify the output of text report shows the merged results.
3. I'm also OK with using `glob`, though this would raise the testing burden a bit.  Specifically we need to make sure that `nyc report --temp-dir 'temp*'` only considers directories, so temp1/ and temp2/ but not temp3.json.

**Comment by AndrewFinlay** [comment]
bump

**Comment by JaKXz** [comment]
Thanks @AndrewFinlay, stale bot won't touch this any more. Want to take a stab at it?

**Comment by AndrewFinlay** [comment]
Sure, leave it with me but it might take a little while to reach the top of the pile.

**Comment by Krinkle** [comment]
@AndrewFinlay [wrote](https://github.com/istanbuljs/nyc/issues/879#issuecomment-407928864)

> This functionality is pretty easily achieved by copying the coverage results from e2e and unit tests to a common directory, then running the reporting tool on that.

I interpreted this as meaning that NYC will recursively scan subdirectories in the given temp directory, which made sense to me given that upon a cursory glance in the `.nyc_output` directory, I do see subdirectories there as well.

I tried the following:

```
# Use --silent so that it will not yet report
$ nyc -t nyc_tmp/nodejs/ --silent qunit test/cli.js

# Uses Headless Chrome and writes coverager data files to nyc_tmp/browser/
$ nyc instrument --in-place dist/ && grunt qunit

$ nyc report  -t nyc_tmp/
```

But this produced an empty report.  It looks like I have to configure my second writer (the browser test in my case) to add the files into the same flattened directory. This feels wrong as I don't know how to safely a avoid file name conflicts in that case, but adding a reasonably unique prefix helps with that.

The following worked for me and allowed me to use get coverage information using Instanbul NYC and QUnit from Node.js, and from QUnit in Headless Chrome with [grunt-contrib-qunit](https://github.com/gruntjs/grunt-contrib-qunit), and have a combined code coverage report.

```
# Use --silent so that it will not yet report
$ nyc --silent qunit test/cli.js

# Uses grunt-contrib-qunit with an injected bridge file that sends window.__coverage__
# from the browser to Grunt using sendMessage(), and then writes to a flattened file name
# into the pre-existing .nyc_output/ directory.
#
#     const testName = suite.replace( ".html", "" ).replace( /[/\\]/g, "--" );
#     const reportPath = path.join( ".nyc_output", "browser--" + testName + ".json" );
#     fs.writeFileSync( reportPath, JSON.stringify( coverage ) + "\n" );
#
$ nyc instrument --in-place dist/ && grunt qunit

# Yay!
$ nyc report
```

For the actual code, see [qunitjs/qunit@1830856b0e](https://github.com/qunitjs/qunit/blob/1830856b0e88966775ecc366c45db0d452733e8a/package.json#L95-L97) for `package.json`, `rollup.config.js`, `Gruntfile.js` and `build/coverage-bridge.js`.
