### ISSUE TITLE
Version 12.0.0 and above causes lint TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by taygrave** [istanbuljs/nyc#888]
## Expected Behavior
Ran `yarn add -D nyc` and got version `13.0.0` installed, expect this not to interfere with linting or introduce new lint errors. 

## Observed Behavior
With `nyc@^13.0.0` freshly installed, when running `yarn lint`, received the following error: 

```
Cannot read property 'range' of null
TypeError: Cannot read property 'range' of null
    at SourceCode.getTokenBefore (/Users/thbm/dev/api/node_modules/eslint/lib/token-store/index.js:303:18)
    at checkSpacingBefore (/Users/thbm/dev/api/node_modules/eslint/lib/rules/template-curly-spacing.js:52:42)
    at TemplateElement (/Users/thbm/dev/api/node_modules/eslint/lib/rules/template-curly-spacing.js:117:17)
    at listeners.(anonymous function).forEach.listener (/Users/thbm/dev/api/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/thbm/dev/api/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/thbm/dev/api/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/thbm/dev/api/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/thbm/dev/api/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/thbm/dev/api/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```

Looks like it has something to do w/ having multiple copies of `@babley/types`: https://github.com/babel/babel-eslint/issues/530#issuecomment-354242702

`npm list @babel/types` get this output:
```
├─┬ babel-eslint@8.2.2
│ ├─┬ @babel/traverse@7.0.0-beta.40
│ │ ├─┬ @babel/generator@7.0.0-beta.40
│ │ │ └── @babel/types@7.0.0-beta.40  deduped
│ │ ├─┬ @babel/helper-function-name@7.0.0-beta.40
│ │ │ ├─┬ @babel/helper-get-function-arity@7.0.0-beta.40
│ │ │ │ └── @babel/types@7.0.0-beta.40 
│ │ │ ├─┬ @babel/template@7.0.0-beta.40
│ │ │ │ └── @babel/types@7.0.0-beta.40  deduped
│ │ │ └── @babel/types@7.0.0-beta.40 
│ │ └── @babel/types@7.0.0-beta.40 
│ └── @babel/types@7.0.0-beta.40 
└─┬ nyc@13.0.0
  └─┬ istanbul-lib-instrument@2.3.1
    ├─┬ @babel/generator@7.0.0-beta.51
    │ └── @babel/types@7.0.0-beta.51  deduped
    ├─┬ @babel/template@7.0.0-beta.51
    │ └── @babel/types@7.0.0-beta.51  deduped
    ├─┬ @babel/traverse@7.0.0-beta.51
    │ ├─┬ @babel/helper-function-name@7.0.0-beta.51
    │ │ ├─┬ @babel/helper-get-function-arity@7.0.0-beta.51
    │ │ │ └── @babel/types@7.0.0-beta.51  deduped
    │ │ └── @babel/types@7.0.0-beta.51  deduped
    │ ├─┬ @babel/helper-split-export-declaration@7.0.0-beta.51
    │ │ └── @babel/types@7.0.0-beta.51  deduped
    │ └── @babel/types@7.0.0-beta.51  deduped
    └── @babel/types@7.0.0-beta.51 
```

I downgraded the `nyc` version until I found one that did not produce this error, that was version `11.9.0` - using that version I can successfully run my linting and `npm ls @babel/types` produces the following: 

```
└─┬ babel-eslint@8.2.2
  ├─┬ @babel/traverse@7.0.0-beta.40
  │ ├─┬ @babel/generator@7.0.0-beta.40
  │ │ └── @babel/types@7.0.0-beta.40  deduped
  │ ├─┬ @babel/helper-function-name@7.0.0-beta.40
  │ │ ├─┬ @babel/helper-get-function-arity@7.0.0-beta.40
  │ │ │ └── @babel/types@7.0.0-beta.40  deduped
  │ │ ├─┬ @babel/template@7.0.0-beta.40
  │ │ │ └── @babel/types@7.0.0-beta.40  deduped
  │ │ └── @babel/types@7.0.0-beta.40  deduped
  │ └── @babel/types@7.0.0-beta.40  deduped
  └── @babel/types@7.0.0-beta.40 
```

## Forensic Information
**Operating System:** MacOS High Sierra
**Environment Information:**
node v8.11.1
npm 6.1.0
babel-eslint 8.2.2 
eslint-plugin-babel 4.1.2
eslint-plugin-flowtype 2.46.1
eslint-plugin-lodash 2.6.1
eslint-plugin-mocha 4.12.1
eslint-scope 3.7.1
eslint-visitor-keys 1.0.0
eslint 4.18.2

**Comment by coreyfarrell** [comment]
I have not experienced this issue, please link to a repository demonstrating this issue.

**Comment by FabioIngrao** [comment]
I confirm that version 12 causes this problem.

**Comment by JaKXz** [comment]
If this is still an issue with the latest version of nyc, please open a new issue with a link to a minimal reproduction repo.
