### ISSUE TITLE
Client coverage report error

### ISSUE THREAD

**Issue by enuggetry** [istanbuljs/nyc#949]
I'm trying to combine server coverage reports with client coverage.  I have no problems generating server coverage reports.  But, I'm having problems understanding how to produce client reports and combining them with server reports.

In my test script, I write `windows.__coverage__` into `.nyc_output/clientreport.json` for pre-instrumented code.

```
after(function(browser,done) {
    browser.execute(function(data) {
        return window.__coverage__;
    },[], function(result) {
        fs.writeFileSync('.nyc_output/coveragetest.json',JSON.stringify(result,null,4));
    });
});
```

which was prescribed in: https://istanbul.js.org/docs/advanced/coverage-object-report/

When I run `nyc report`, I get the following error:
```
nyc report --reporter=text
/home/ericiam/jbconnect/node_modules/nyc/node_modules/yargs/yargs.js:1133
      else throw err
           ^

Error: Coverage must be initialized with a path or an object
    at new FileCoverage (/home/ericiam/jbconnect/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/file.js:153:15)
    at /home/ericiam/jbconnect/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/coverage-map.js:17:23
    at Array.forEach (<anonymous>)
    at loadMap (/home/ericiam/jbconnect/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/coverage-map.js:12:25)
    at new CoverageMap (/home/ericiam/jbconnect/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/coverage-map.js:34:21)
    at CoverageMap.merge (/home/ericiam/jbconnect/node_modules/nyc/node_modules/istanbul-lib-coverage/lib/coverage-map.js:49:17)
    at eachReport (/home/ericiam/jbconnect/node_modules/nyc/index.js:425:9)
    at /home/ericiam/jbconnect/node_modules/nyc/index.js:540:5
    at Array.forEach (<anonymous>)
    at NYC.eachReport (/home/ericiam/jbconnect/node_modules/nyc/index.js:527:9)

```

I'm new to Istanbul.  What am I missing?

**Comment by lqin-pki** [comment]
@enuggetry after read nyc's source, I realized that we should write window.__coverage__.value to the file before running the nyc report.

**Comment by JaKXz** [comment]
@enuggetry sorry for the late reply - can you please provide a minimal reproduction in a public repo?

**Comment by bcoe** [comment]
closing as stale, @enuggetry or @lqin-pki please feel free to open a new repository with a minimal reproduction :+1:

**Comment by anzemur** [comment]
Is there any news on this issue? I am running `nyc report` on multiple json output files and I am getting the same error.

@JaKXz

**Comment by JaKXz** [comment]
Please open a new issue with the latest version of NYC and all the requirements in the new issue template, especially a minimal demo repo.

**Comment by acoss22** [comment]
I am dealing with this issue as well, any fix?
