### ISSUE TITLE
spawn-wrap causes failure due to unwritable homedir

### ISSUE THREAD

**Issue by Krinkle** [istanbuljs/nyc#951]
## Observed Behavior

When using nyc as a system user that is not allowed to write to its home directory (e.g. `HOME=/nonexistent`), a command like `nyc qunit test` or some other use of nyc fails as follows:

```
+ npm run-script test

> nyc -r text -r html qunit test/

/src/node_modules/nyc/node_modules/mkdirp/index.js:90
                    throw err0;
                    ^

Error: EACCES: permission denied, mkdir '/nonexistent'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at sync (/src/node_modules/nyc/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/src/node_modules/nyc/node_modules/mkdirp/index.js:77:24)
    at setup (/src/node_modules/nyc/node_modules/spawn-wrap/index.js:414:10)
    at wrap (/src/node_modules/nyc/node_modules/spawn-wrap/index.js:60:18)
    at Object.<anonymous> (/src/node_modules/nyc/bin/nyc.js:57:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

I believe this is because spawn-wrap, unlike nyc, defaults to using a a sub directory of `HOME` as its working directory. Instead of using process.cwd() or TMPDIR etc, like nyc does.

This should probably be fixed upstream in spawn-wrap, but could be worked around in nyc by passing NYC_CWD as the `workingDir` parameter to the spawn-wrap function.

Currently ([nyc@v13.1.0:/bin/nyc.js](https://github.com/istanbuljs/nyc/blob/v13.1.0/bin/nyc.js#L44-L57)), nyc invokes spwan-wrap with two parameters, leaving the third parameter (workingDir) unset. In spawn-wrap ([spawn-wrap:/index.js](https://github.com/tapjs/spawn-wrap/blob/v1.4.2/index.js#L40), this means it defaults to the setup of creating a directory in the os-home directory.

```
Node v11.4.0
npm 6.5.0
```

**Comment by Krinkle** [comment]
For the record, I was able to workaround this bug by forcing spawn-wrap to use a the current working directory instead, through the environment variable it considers:

```
	"@script.test": "# see spawn-wrap bug at https://github.com/istanbuljs/nyc/issues/951",
	"scripts": {
		"test": "SPAWN_WRAP_SHIM_ROOT=. nyc -r text -r html qunit test/"
	},
```
